import Foundation
import KawarimiCore
import OpenAPIKit
import Yams

public enum KawarimiJutsu {
    public static func loadOpenAPISpec(path: String) throws -> OpenAPI.Document {
        try OpenAPIDocumentLoader.load(path: path)
    }

    public static func generateSwiftSource(document: OpenAPI.Document) -> String {
        let cases = generateTransportCases(document: document)
        return """
            // Generated by Kawarimi. Do not edit.

            import Foundation
            import OpenAPIRuntime
            import HTTPTypes

            public struct Kawarimi: ClientTransport {
                public init() {}
                public func send(_ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String) async throws -> (HTTPResponse, HTTPBody?) {
                    switch operationID {
            \(cases)
                    default:
                        return (HTTPResponse(status: .notFound), nil)
                    }
                }
            }
            """
    }

    // MARK: - Mock transport generation

    private enum TransportMockResponse {
        case json(statusSwiftName: String, body: String)
        case noContent
    }

    private static func generateTransportCases(document: OpenAPI.Document) -> String {
        var lines: [String] = []
        let components = document.components

        for route in document.routes {
            for endpoint in route.pathItem.endpoints {
                let operation = endpoint.operation
                guard let operationId = operation.operationId, !operationId.isEmpty else { continue }

                let mock = defaultTransportResponse(
                    operation: operation,
                    components: components,
                    operationId: operationId
                )
                lines.append("                    case \"\(operationId)\":")
                switch mock {
                case .json(let statusSwiftName, let jsonBody):
                    let escaped = escapeForSwiftStringLiteral(jsonBody)
                    lines.append(
                        "                        return (HTTPResponse(status: .\(statusSwiftName)), HTTPBody(\"\(escaped)\"))"
                    )
                case .noContent:
                    lines.append("                        return (HTTPResponse(status: .noContent), nil)")
                }
            }
        }
        return lines.joined(separator: "\n")
    }

    private static func escapeForSwiftStringLiteral(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
    }

    private static func defaultTransportResponse(
        operation: OpenAPI.Operation,
        components: OpenAPI.Components,
        operationId: String
    ) -> TransportMockResponse {
        for code in [200, 201] {
            let statusCode = OpenAPI.Response.StatusCode.status(code: code)
            guard let responseEither = operation.responses[status: statusCode],
                  let response = components[responseEither],
                  let content = response.content[.json] else { continue }
            let json = mockJSONBodyFromJSONMediaType(
                content: content,
                components: components,
                operationId: operationId,
                diagnosticPath: "responses.\(code).content['application/json']"
            )
            let statusSwiftName = code == 200 ? "ok" : "created"
            return .json(statusSwiftName: statusSwiftName, body: json)
        }
        if operation.responses[status: OpenAPI.Response.StatusCode.status(code: 204)] != nil {
            return .noContent
        }
        return .json(statusSwiftName: "ok", body: "{}")
    }

    private static func mockJSONBodyFromJSONMediaType(
        content: OpenAPI.Content,
        components: OpenAPI.Components,
        operationId: String,
        diagnosticPath: String
    ) -> String {
        let (json, warnings) = mockJSONBodyFromJSONMediaTypeWithWarnings(
            content: content,
            components: components,
            operationId: operationId,
            diagnosticPath: diagnosticPath
        )
        for warning in warnings {
            StandardError.write(warning)
        }
        return json
    }

    private static func mockJSONBodyFromJSONMediaTypeWithWarnings(
        content: OpenAPI.Content,
        components: OpenAPI.Components,
        operationId: String,
        diagnosticPath: String
    ) -> (json: String, warnings: [String]) {
        if let exampleJSON = exampleToJSONString(content.example) {
            return (exampleJSON, [])
        }
        guard let schemaEither = content.schema else { return ("{}", []) }
        var refChain = Set<OpenAPI.ComponentKey>()
        var synthesisContext = MockJSONSynthesisContext(
            operationId: operationId,
            diagnosticPath: "\(diagnosticPath).schema"
        )
        let json: String
        switch schemaEither {
        case .a(let ref):
            guard let name = ref.name,
                  let key = OpenAPI.ComponentKey(rawValue: name),
                  let schema = components.schemas[key] else {
                return ("{}", [])
            }
            json = defaultJSONForSchema(
                schema,
                components: components,
                refChain: &refChain,
                synthesisContext: &synthesisContext
            )
        case .b(let schema):
            json = defaultJSONForSchema(
                schema,
                components: components,
                refChain: &refChain,
                synthesisContext: &synthesisContext
            )
        }
        return (json, synthesisContext.warnings)
    }

    internal static func testingMockJSONBody(
        document: OpenAPI.Document,
        operationId: String,
        statusCode: Int
    ) -> (body: String, warnings: [String])? {
        let status = OpenAPI.Response.StatusCode.status(code: statusCode)
        for route in document.routes {
            for endpoint in route.pathItem.endpoints {
                guard endpoint.operation.operationId == operationId else { continue }
                guard let responseEither = endpoint.operation.responses[status: status],
                      let response = document.components[responseEither],
                      let content = response.content[.json]
                else { return nil }
                let result = mockJSONBodyFromJSONMediaTypeWithWarnings(
                    content: content,
                    components: document.components,
                    operationId: operationId,
                    diagnosticPath: "responses.\(statusCode).content['application/json']"
                )
                return (body: result.json, warnings: result.warnings)
            }
        }
        return nil
    }

    private static func schemaPrimaryExample(_ schema: JSONSchema) -> AnyCodable? {
        schema.examples.first
    }

    private static func defaultJSONForSchema(
        _ schema: JSONSchema,
        components: OpenAPI.Components,
        refChain: inout Set<OpenAPI.ComponentKey>,
        synthesisContext: inout MockJSONSynthesisContext,
        fieldPath: String = ""
    ) -> String {
        if case .reference(let ref, _) = schema.value,
           let name = ref.name,
           let key = OpenAPI.ComponentKey(rawValue: name)
        {
            if refChain.contains(key) { return "{}" }
            guard let inner = components.schemas[key] else {
                return defaultJSONForSchemaCore(
                    schema,
                    components: components,
                    refChain: &refChain,
                    synthesisContext: &synthesisContext,
                    fieldPath: fieldPath
                )
            }
            refChain.insert(key)
            defer { refChain.remove(key) }
            return defaultJSONForSchema(
                inner,
                components: components,
                refChain: &refChain,
                synthesisContext: &synthesisContext,
                fieldPath: fieldPath
            )
        }
        return defaultJSONForSchemaCore(
            schema,
            components: components,
            refChain: &refChain,
            synthesisContext: &synthesisContext,
            fieldPath: fieldPath
        )
    }

    private static func defaultJSONForSchemaCore(
        _ schema: JSONSchema,
        components: OpenAPI.Components,
        refChain: inout Set<OpenAPI.ComponentKey>,
        synthesisContext: inout MockJSONSynthesisContext,
        fieldPath: String
    ) -> String {
        let resolved = schema

        if OpenAPIDateMockSupport.isOpenAPIAbsoluteDateStringSchema(resolved) {
            return OpenAPIDateMockSupport.jsonFragmentForDateSchema(
                resolved: resolved,
                synthesisContext: &synthesisContext,
                fieldPath: fieldPath
            )
        }

        if let exampleJSON = exampleToJSONString(schemaPrimaryExample(resolved)) {
            return exampleJSON
        }
        if let defaultJSON = exampleToJSONString(resolved.defaultValue) {
            return defaultJSON
        }

        if let objectContext = resolved.objectContext {
            let pairs = objectContext.properties.map { name, propSchema -> String in
                let childPath = fieldPath.isEmpty ? "properties.\(name)" : "\(fieldPath).properties.\(name)"
                let value = defaultJSONForSchema(
                    propSchema,
                    components: components,
                    refChain: &refChain,
                    synthesisContext: &synthesisContext,
                    fieldPath: childPath
                )
                return "\"\(name)\": \(value)"
            }
            return "{\(pairs.joined(separator: ", "))}"
        }

        if let arrayContext = resolved.arrayContext {
            guard let itemsSchema = arrayContext.items else {
                return "[]"
            }
            let itemsPath = fieldPath.isEmpty ? "items" : "\(fieldPath).items"
            let itemJSON = defaultJSONForSchema(
                itemsSchema,
                components: components,
                refChain: &refChain,
                synthesisContext: &synthesisContext,
                fieldPath: itemsPath
            )
            return "[\(itemJSON)]"
        }

        switch resolved.value {
        case .one(of: let schemas, core: _), .any(of: let schemas, core: _):
            for sub in schemas {
                let j = defaultJSONForSchema(
                    sub,
                    components: components,
                    refChain: &refChain,
                    synthesisContext: &synthesisContext,
                    fieldPath: fieldPath
                )
                if !isVacuousJSONMock(j) { return j }
            }
            if let first = schemas.first {
                return defaultJSONForSchema(
                    first,
                    components: components,
                    refChain: &refChain,
                    synthesisContext: &synthesisContext,
                    fieldPath: fieldPath
                )
            }
            return "{}"
        case .all(of: let schemas, core: _):
            var merged: [String: Any] = [:]
            for sub in schemas {
                let j = defaultJSONForSchema(
                    sub,
                    components: components,
                    refChain: &refChain,
                    synthesisContext: &synthesisContext,
                    fieldPath: fieldPath
                )
                guard let data = j.data(using: .utf8),
                      let obj = try? JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]) as? [String: Any]
                else { continue }
                for (k, v) in obj {
                    merged[k] = v
                }
            }
            if !merged.isEmpty {
                if let data = try? JSONSerialization.data(withJSONObject: merged, options: [.sortedKeys]),
                   let s = String(data: data, encoding: .utf8)
                {
                    return s
                }
            }
            if let first = schemas.first {
                return defaultJSONForSchema(
                    first,
                    components: components,
                    refChain: &refChain,
                    synthesisContext: &synthesisContext,
                    fieldPath: fieldPath
                )
            }
            return "{}"
        case .not:
            return "{}"
        default:
            break
        }

        if let allowed = resolved.allowedValues, let first = allowed.first,
           let j = exampleToJSONString(first) {
            return j
        }

        switch resolved.jsonType {
        case .some(.string): return "\"\""
        case .some(.integer): return "0"
        case .some(.number): return "0.0"
        case .some(.boolean): return "false"
        default: return "{}"
        }
    }

    /// True for placeholder-shaped JSON when probing oneOf branches or object composition.
    private static func isVacuousJSONMock(_ json: String) -> Bool {
        let t = json.trimmingCharacters(in: .whitespacesAndNewlines)
        switch t {
        case "{}", "\"\"", "0", "0.0", "false", "[]": return true
        default: return false
        }
    }

    private static func exampleToJSONString(_ example: AnyCodable?) -> String? {
        guard let example else { return nil }
        guard let data = try? JSONEncoder().encode(example),
              let s = String(data: data, encoding: .utf8) else { return nil }
        return s
    }

    public static func generateKawarimiHandlerSource(
        document: OpenAPI.Document,
        namingStrategy: KawarimiNamingStrategy = KawarimiGeneratorConfigYAML.defaults.namingStrategy,
        accessModifier: KawarimiAccessModifier = KawarimiGeneratorConfigYAML.defaults.accessModifier,
        handlerStubPolicy: KawarimiHandlerStubPolicy = KawarimiGeneratorConfigYAML.defaults.handlerStubPolicy
    ) throws -> (source: String, warnings: [String]) {
        let (methods, warnings, fatalErrorStubIndex) = try generateHandlerMethods(
            document: document,
            namingStrategy: namingStrategy,
            accessKeyword: accessModifier.swiftKeyword,
            handlerStubPolicy: handlerStubPolicy
        )
        var allWarnings = warnings
        if !fatalErrorStubIndex.isEmpty {
            allWarnings.append(
                stderrSummaryForFatalErrorStubs(operationIds: fatalErrorStubIndex.map(\.operationId))
            )
        }
        let indexComment = fatalErrorStubSourceCommentBlock(entries: fatalErrorStubIndex)
        let source = """
            // Generated by Kawarimi. Do not edit.\(indexComment)

            import Foundation
            import OpenAPIRuntime
            import HTTPTypes

            public struct KawarimiHandler: APIProtocol {
                public init() {}
            \(OpenAPIDateMockSupport.generatedStubJSONDecoderMethodSource())
            \(methods)
            }
            """
        return (source, allWarnings)
    }

    private static func handlerWitnessPropertyName(methodName: String) -> String {
        guard let first = methodName.first else { return "onOperation" }
        return "on" + String(first).uppercased() + methodName.dropFirst()
    }

    private static func openapiOperationContextLabel(routePath: String, httpMethod: String) -> String {
        "[\(httpMethod.uppercased()) \(routePath)] "
    }

    private static func stubClosureBodyLines(stub: HandlerOutputStub) -> [String] {
        switch stub {
        case .okJSON(let expr):
            return ["        return .ok(.init(body: .json(\(expr))))"]
        case .okJSONDecoded(let payloadTypeName, let jsonLiteralEscaped):
            return [
                "        let _kawarimiStubData = Data(\"\(jsonLiteralEscaped)\".utf8)",
                "        let _kawarimiDecodedBody = try Self._kawarimiStubJSONDecoder().decode(\(payloadTypeName).self, from: _kawarimiStubData)",
                "        return .ok(.init(body: .json(_kawarimiDecodedBody)))",
            ]
        case .okEmpty:
            return ["        return .ok(.init())"]
        case .createdJSON(let expr):
            return ["        return .created(.init(body: .json(\(expr))))"]
        case .createdJSONDecoded(let payloadTypeName, let jsonLiteralEscaped):
            return [
                "        let _kawarimiStubData = Data(\"\(jsonLiteralEscaped)\".utf8)",
                "        let _kawarimiDecodedBody = try Self._kawarimiStubJSONDecoder().decode(\(payloadTypeName).self, from: _kawarimiStubData)",
                "        return .created(.init(body: .json(_kawarimiDecodedBody)))",
            ]
        case .createdEmpty:
            return ["        return .created(.init())"]
        case .noContent:
            return ["        return .noContent(.init())"]
        case .unsupportedFatalError(let operationId, let detail):
            let msg =
                "Kawarimi: KawarimiHandler stub unsupported (operationId: \(operationId)): \(detail)"
            let escaped = escapeForSwiftStringLiteral(msg)
            return ["        fatalError(\"\(escaped)\")"]
        }
    }

    private static func stderrWarningForFatalErrorStub(operationId: String, detail: String) -> String {
        "Kawarimi warning: KawarimiHandler: using fatalError() stub for operationId \(operationId); \(detail) Use handlerStubPolicy: throw or omit the key (fail-fast default since 0.7) to fail generation instead."
    }

    /// Safe for `// …` lines (no `*/`, no newlines).
    private static func sanitizeForSourceCommentLine(_ s: String) -> String {
        s.replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\r", with: " ")
            .replacingOccurrences(of: "*/", with: "* /")
    }

    private static func fatalErrorStubSourceCommentBlock(entries: [(operationId: String, routeLabel: String)]) -> String {
        guard !entries.isEmpty else { return "" }
        var lines: [String] = [
            "",
            "// Kawarimi: handlerStubPolicy fatalError — operations below use fatalError() stub bodies.",
            "//   Override with the matching on… closure, or use handlerStubPolicy: throw (or omit; default) to fail at codegen.",
        ]
        for e in entries {
            let id = sanitizeForSourceCommentLine(e.operationId)
            let label = sanitizeForSourceCommentLine(e.routeLabel)
            lines.append("//   \(label) \(id)")
        }
        return lines.joined(separator: "\n")
    }

    private static func stderrSummaryForFatalErrorStubs(operationIds: [String]) -> String {
        let n = operationIds.count
        let noun = n == 1 ? "operation" : "operations"
        let list = operationIds.map { sanitizeForSourceCommentLine($0) }.joined(separator: ", ")
        return "Kawarimi warning: Summary: \(n) \(noun) use fatalError stubs: \(list)"
    }

    private static func stderrWarningForSkippedCodegenMissingOperationId(httpMethod: String, routePath: String) -> String {
        "[kawarimi] warning: operation \(httpMethod) \(routePath) has no operationId and will be skipped"
    }

    private static func generateHandlerMethods(
        document: OpenAPI.Document,
        namingStrategy: KawarimiNamingStrategy,
        accessKeyword: String,
        handlerStubPolicy: KawarimiHandlerStubPolicy
    ) throws -> (String, [String], [(operationId: String, routeLabel: String)]) {
        var lines: [String] = []
        var warnings: [String] = []
        var fatalErrorStubIndex: [(operationId: String, routeLabel: String)] = []
        let components = document.components

        for route in document.routes {
            let routePath = route.path.rawValue
            for endpoint in route.pathItem.endpoints {
                let operation = endpoint.operation
                guard let operationId = operation.operationId, !operationId.isEmpty else {
                    let httpMethod = endpoint.method.rawValue.uppercased()
                    warnings.append(stderrWarningForSkippedCodegenMissingOperationId(httpMethod: httpMethod, routePath: routePath))
                    continue
                }
                let httpMethod = endpoint.method.rawValue
                let opContext = openapiOperationContextLabel(routePath: routePath, httpMethod: httpMethod)
                let typeName = try namingStrategy.swiftOperationTypeName(forOperationId: operationId)
                let methodName = try namingStrategy.swiftOperationMethodName(forOperationId: operationId)
                let witnessName = handlerWitnessPropertyName(methodName: methodName)
                let inputType = "Operations.\(typeName).Input"
                let outputType = "Operations.\(typeName).Output"
                let stub: HandlerOutputStub
                switch handlerStubPolicy {
                case .throw:
                    stub = try selectHandlerStubResponse(
                        operation: operation,
                        components: components,
                        operationId: operationId,
                        operationContext: opContext,
                        operationSwiftTypeName: typeName,
                        namingStrategy: namingStrategy,
                        handlerStubWarnings: &warnings
                    )
                case .fatalError:
                    do {
                        stub = try selectHandlerStubResponse(
                            operation: operation,
                            components: components,
                            operationId: operationId,
                            operationContext: opContext,
                            operationSwiftTypeName: typeName,
                            namingStrategy: namingStrategy,
                            handlerStubWarnings: &warnings
                        )
                    } catch let error as KawarimiJutsuError {
                        guard case .handlerGenerationUnsupported(_, let detail) = error else { throw error }
                        warnings.append(stderrWarningForFatalErrorStub(operationId: operationId, detail: detail))
                        let label = opContext.trimmingCharacters(in: .whitespaces)
                        fatalErrorStubIndex.append((operationId: operationId, routeLabel: label))
                        stub = .unsupportedFatalError(operationId: operationId, detail: detail)
                    }
                }
                lines.append(
                    "    \(accessKeyword) var \(witnessName): @Sendable (\(inputType)) async throws -> \(outputType) = { _ in"
                )
                lines.append(contentsOf: stubClosureBodyLines(stub: stub))
                lines.append("    }")
                lines.append("    \(accessKeyword) func \(methodName)(_ input: \(inputType)) async throws -> \(outputType) {")
                lines.append("        try await \(witnessName)(input)")
                lines.append("    }")
            }
        }
        return (lines.joined(separator: "\n"), warnings, fatalErrorStubIndex)
    }

    private enum HandlerOutputStub {
        case okJSON(String)
        case okJSONDecoded(payloadTypeName: String, jsonLiteralEscaped: String)
        case okEmpty
        case createdJSON(String)
        case createdJSONDecoded(payloadTypeName: String, jsonLiteralEscaped: String)
        case createdEmpty
        case noContent
        case unsupportedFatalError(operationId: String, detail: String)
    }

    private static func selectHandlerStubResponse(
        operation: OpenAPI.Operation,
        components: OpenAPI.Components,
        operationId: String,
        operationContext: String,
        operationSwiftTypeName: String,
        namingStrategy: KawarimiNamingStrategy,
        handlerStubWarnings: inout [String]
    ) throws -> HandlerOutputStub {
        for code in [200, 201] {
            let statusCode = OpenAPI.Response.StatusCode.status(code: code)
            guard let responseEither = operation.responses[status: statusCode],
                  let response = components[responseEither] else { continue }

            if let content = response.content[.json] {
                let initializerExpr: String?
                do {
                    initializerExpr = try bodyExprForResponse(
                        response: response,
                        components: components,
                        operationId: operationId,
                        operationContext: operationContext,
                        httpStatus: code,
                        namingStrategy: namingStrategy,
                        handlerStubWarnings: &handlerStubWarnings
                    )
                } catch {
                    initializerExpr = nil
                }
                if let expr = initializerExpr {
                    return code == 200 ? .okJSON(expr) : .createdJSON(expr)
                }
                let json = mockJSONBodyFromJSONMediaType(
                    content: content,
                    components: components,
                    operationId: operationId,
                    diagnosticPath:
                        "\(operationContext)responses.\(code).content['application/json']"
                )
                let escaped = escapeForSwiftStringLiteral(json)
                let payloadType = try handlerStubJSONPayloadSwiftType(
                    operationSwiftTypeName: operationSwiftTypeName,
                    httpStatus: code,
                    content: content,
                    namingStrategy: namingStrategy
                )
                return code == 200
                    ? .okJSONDecoded(payloadTypeName: payloadType, jsonLiteralEscaped: escaped)
                    : .createdJSONDecoded(payloadTypeName: payloadType, jsonLiteralEscaped: escaped)
            }

            if response.content.isEmpty {
                if let headers = response.headers, !headers.isEmpty {
                    throw KawarimiJutsuError.handlerGenerationUnsupported(
                        operationId: operationId,
                        detail:
                            "\(operationContext)HTTP \(code) declares response headers but no body. Cannot emit stub initializers automatically; implement the `on…` closure manually or adjust the headers."
                    )
                }
                return code == 200 ? .okEmpty : .createdEmpty
            }

            throw KawarimiJutsuError.handlerGenerationUnsupported(
                operationId: operationId,
                detail:
                    "\(operationContext)HTTP \(code) includes non-JSON content. Kawarimi only stubs 200/201 with a JSON body or without content."
            )
        }
        if operation.responses[status: OpenAPI.Response.StatusCode.status(code: 204)] != nil {
            return .noContent
        }
        throw KawarimiJutsuError.handlerGenerationUnsupported(
            operationId: operationId,
            detail:
                "\(operationContext)Requires HTTP 200 / 201 (JSON or no content) or 204. Only stubs aligned with swift-openapi-generator Operations output are generated."
        )
    }

    private static func bodyExprForResponse(
        response: OpenAPI.Response,
        components: OpenAPI.Components,
        operationId: String,
        operationContext: String,
        httpStatus: Int,
        namingStrategy: KawarimiNamingStrategy,
        handlerStubWarnings: inout [String]
    ) throws -> String? {
        guard let content = response.content[.json] else { return nil }
        guard let schema = resolveSchemaFromContent(content: content, components: components) else { return nil }
        let schemaHint = schemaDiagnosticHint(content: content, components: components)
        let path =
            "\(operationContext)OpenAPI JSON path: paths · … · responses.\(httpStatus).content['application/json'].schema\(schemaHint.map { " → \($0)" } ?? "")"
        var refChain = Set<OpenAPI.ComponentKey>()
        return try swiftInitializerForSchema(
            schema,
            components: components,
            operationId: operationId,
            diagnosticPath: path,
            namingStrategy: namingStrategy,
            handlerStubWarnings: &handlerStubWarnings,
            refChain: &refChain
        )
    }

    private static func schemaDiagnosticHint(content: OpenAPI.Content, components: OpenAPI.Components) -> String? {
        guard let schemaEither = content.schema else { return nil }
        switch schemaEither {
        case .a(let ref):
            return ref.name.map { "components.schemas.\($0)" }
        case .b:
            return nil
        }
    }

    private static func resolveSchemaFromContent(content: OpenAPI.Content, components: OpenAPI.Components) -> JSONSchema? {
        guard let schemaEither = content.schema else { return nil }
        switch schemaEither {
        case .a(let ref):
            return components[ref]
        case .b(let schema):
            return schema
        }
    }

    /// Swift type passed to `JSONDecoder` for `application/json` bodies, aligned with swift-openapi-generator.
    private static func handlerStubJSONPayloadSwiftType(
        operationSwiftTypeName: String,
        httpStatus: Int,
        content: OpenAPI.Content,
        namingStrategy: KawarimiNamingStrategy
    ) throws -> String {
        let outputCase = httpStatus == 201 ? "Created" : "Ok"
        let jsonPayload = "Operations.\(operationSwiftTypeName).Output.\(outputCase).Body.jsonPayload"
        guard let schemaEither = content.schema else { return jsonPayload }
        switch schemaEither {
        case .a(let ref):
            if let name = ref.name {
                // `ref.name` is the raw OpenAPI component name; sanitize it to the Swift
                // identifier swift-openapi-generator actually emits (e.g. `Error` -> `_Error`).
                return try "Components.Schemas.\(namingStrategy.swiftSchemaTypeName(for: name))"
            }
            return jsonPayload
        case .b:
            return jsonPayload
        }
    }

    private static func pathPrefix(in document: OpenAPI.Document) -> String {
        guard let raw = document.servers.first?.urlTemplate.rawValue, !raw.isEmpty,
              let url = URL(string: raw) else {
            return ""
        }
        let path = url.path
        if path.isEmpty || path == "/" {
            return ""
        }
        return KawarimiPath.joinPathPrefix(KawarimiPath.splitPathSegments(path))
    }

    // MARK: - KawarimiSpec source emission

    private struct SpecSecuritySchemeEntry {
        var name: String
        var type: String
        var description: String?
        var apiKeyName: String?
        var apiKeyIn: String?
        var httpScheme: String?
        var bearerFormat: String?
        var openIdConnectURL: String?
    }

    private struct SpecScopedSecurityEntry {
        var name: String
        var scopes: [String]
    }

    private struct SpecSecurityRequirementEntry {
        var schemes: [SpecScopedSecurityEntry]
    }

    private static func securitySchemeLocationString(_ location: OpenAPI.SecurityScheme.Location) -> String {
        switch location {
        case .query: return "query"
        case .header: return "header"
        case .cookie: return "cookie"
        }
    }

    private static func securitySchemeEntries(from components: OpenAPI.Components) -> [SpecSecuritySchemeEntry] {
        guard !components.securitySchemes.isEmpty else { return [] }
        let sortedNames = components.securitySchemes.keys.sorted { $0.rawValue < $1.rawValue }
        var out: [SpecSecuritySchemeEntry] = []
        for name in sortedNames {
            guard let scheme = components.securitySchemes[name] else { continue }
            let typeName = scheme.type.name.rawValue
            var entry = SpecSecuritySchemeEntry(
                name: name.rawValue,
                type: typeName,
                description: scheme.description,
                apiKeyName: nil,
                apiKeyIn: nil,
                httpScheme: nil,
                bearerFormat: nil,
                openIdConnectURL: nil
            )
            switch scheme.type {
            case .apiKey(name: let keyName, location: let location):
                entry.apiKeyName = keyName
                entry.apiKeyIn = securitySchemeLocationString(location)
            case .http(scheme: let httpScheme, bearerFormat: let bearerFormat):
                entry.httpScheme = httpScheme
                entry.bearerFormat = bearerFormat
            case .openIdConnect(openIdConnectUrl: let url):
                entry.openIdConnectURL = url.absoluteString
            case .oauth2, .mutualTLS:
                break
            }
            out.append(entry)
        }
        return out
    }

    private static func scopedSecurityEntries(from requirement: OpenAPI.SecurityRequirement) -> [SpecScopedSecurityEntry] {
        let pairs = requirement.compactMap { ref, scopes -> SpecScopedSecurityEntry? in
            guard let name = ref.name else { return nil }
            return SpecScopedSecurityEntry(name: name, scopes: scopes)
        }
        return pairs.sorted { $0.name < $1.name }
    }

    private static func effectiveSecurityRequirementEntries(
        operation: OpenAPI.Operation,
        document: OpenAPI.Document
    ) -> [SpecSecurityRequirementEntry]? {
        let raw: [OpenAPI.SecurityRequirement]
        if let operationSecurity = operation.security {
            raw = operationSecurity
        } else {
            raw = document.security
        }
        if raw.isEmpty { return nil }
        return raw.map { SpecSecurityRequirementEntry(schemes: scopedSecurityEntries(from: $0)) }
    }

    private static func optionalStringLiteral(_ value: String?) -> String {
        value.map { "\"\(escapeForSwiftStringLiteral($0))\"" } ?? "nil"
    }

    private static func securitySchemeStructLiteral(_ entry: SpecSecuritySchemeEntry) -> String {
        """
                SecurityScheme(
                    name: "\(escapeForSwiftStringLiteral(entry.name))",
                    type: "\(escapeForSwiftStringLiteral(entry.type))",
                    description: \(optionalStringLiteral(entry.description)),
                    apiKeyName: \(optionalStringLiteral(entry.apiKeyName)),
                    apiKeyIn: \(optionalStringLiteral(entry.apiKeyIn)),
                    httpScheme: \(optionalStringLiteral(entry.httpScheme)),
                    bearerFormat: \(optionalStringLiteral(entry.bearerFormat)),
                    openIdConnectURL: \(optionalStringLiteral(entry.openIdConnectURL))
                ),
"""
    }

    private static func scopedSecuritySchemeStructLiteral(_ entry: SpecScopedSecurityEntry) -> String {
        let scopesLiteral: String
        if entry.scopes.isEmpty {
            scopesLiteral = "nil"
        } else {
            let parts = entry.scopes.map { "\"\(escapeForSwiftStringLiteral($0))\"" }.joined(separator: ", ")
            scopesLiteral = "[\(parts)]"
        }
        return """
                            ScopedSecurityScheme(
                                name: "\(escapeForSwiftStringLiteral(entry.name))",
                                scopes: \(scopesLiteral)
                            ),
"""
    }

    private static func securityRequirementStructLiteral(_ entry: SpecSecurityRequirementEntry) -> String {
        let schemesBlock = entry.schemes.map(scopedSecuritySchemeStructLiteral).joined()
        return """
                        SecurityRequirement(
                            schemes: [
            \(schemesBlock)
                            ]
                        ),
"""
    }

    private static func endpointSecurityLiteral(_ requirements: [SpecSecurityRequirementEntry]?) -> String {
        guard let requirements, !requirements.isEmpty else { return "security: nil,\n" }
        let block = requirements.map(securityRequirementStructLiteral).joined()
        return """
                        security: [
            \(block)
                        ],
"""
    }

    private static func specParameterStructLiteral(_ parameter: SpecParameter) -> String {
        let descriptionLiteral = parameter.description.map { "\"\(escapeForSwiftStringLiteral($0))\"" } ?? "nil"
        let schemaTypeLiteral = parameter.schemaType.map { "\"\(escapeForSwiftStringLiteral($0))\"" } ?? "nil"
        return """
                        SpecParameter(
                            location: .\(parameter.location.rawValue),
                            name: "\(escapeForSwiftStringLiteral(parameter.name))",
                            required: \(parameter.required),
                            description: \(descriptionLiteral),
                            schemaType: \(schemaTypeLiteral)
                        ),
"""
    }

    private static func endpointParametersLiteral(_ parameters: [SpecParameter]?) -> String {
        guard let parameters, !parameters.isEmpty else { return "parameters: nil,\n" }
        let block = parameters.map(specParameterStructLiteral).joined()
        return """
                        parameters: [
            \(block)
                        ],
"""
    }

    private static func securitySchemesPropertyLiteral(_ entries: [SpecSecuritySchemeEntry]) -> String {
        if entries.isEmpty {
            return "public static let securitySchemes: [SecurityScheme]? = nil"
        }
        let block = entries.map(securitySchemeStructLiteral).joined()
        return """
                public static let securitySchemes: [SecurityScheme]? = [
            \(block)
                ]
"""
    }

    private struct NamedJSONExample {
        let mapKey: String
        let json: String
        let summary: String?
    }

    private struct SpecResponseRow {
        var statusCode: Int
        var responseMapKey: String
        var mockExampleIdLiteral: String
        var contentType: String
        var body: String
        var responseDescription: String?
        var summaryLiteral: String
    }

    /// OpenAPI `examples` map entries with inline JSON values (skips `externalValue`).
    private static func namedJSONExamples(from content: OpenAPI.Content, components: OpenAPI.Components) -> [NamedJSONExample]? {
        guard let map = content.examples, !map.isEmpty else { return nil }
        var out: [NamedJSONExample] = []
        for (name, either) in map {
            guard let example = components[either] else { continue }
            guard case let .b(value)? = example.value else { continue }
            guard let json = exampleToJSONString(value) else { continue }
            out.append(NamedJSONExample(mapKey: name, json: json, summary: example.summary))
        }
        if out.isEmpty { return nil }
        out.sort { $0.mapKey < $1.mapKey }
        return out
    }

    private static func specResponseRows(
        statusCode: Int,
        jsonContent: OpenAPI.Content,
        responseDescription: String?,
        components: OpenAPI.Components,
        operationId: String
    ) -> [SpecResponseRow] {
        if let named = namedJSONExamples(from: jsonContent, components: components), !named.isEmpty {
            return named.map { item in
                let idLit = "\"\(escapeForSwiftStringLiteral(item.mapKey))\""
                let summ = item.summary.map { "\"\(escapeForSwiftStringLiteral($0))\"" } ?? "nil"
                return SpecResponseRow(
                    statusCode: statusCode,
                    responseMapKey: item.mapKey,
                    mockExampleIdLiteral: idLit,
                    contentType: "application/json",
                    body: item.json,
                    responseDescription: responseDescription,
                    summaryLiteral: summ
                )
            }
        }
        let body = responseBodyJSON(
            content: jsonContent,
            components: components,
            operationId: operationId,
            statusCode: statusCode
        )
        return [SpecResponseRow(
            statusCode: statusCode,
            responseMapKey: KawarimiExampleIds.defaultResponseMapKey,
            mockExampleIdLiteral: "nil",
            contentType: "application/json",
            body: body,
            responseDescription: responseDescription,
            summaryLiteral: "nil"
        )]
    }

    public static func generateKawarimiSpecSource(document: OpenAPI.Document) -> String {
        let info = document.info
        let title = info.title
        let version = info.version
        let description = info.description

        let serverURLString = document.servers.first?.urlTemplate.rawValue ?? ""
        let apiPathPrefix = pathPrefix(in: document)
        let apiPathPrefixEscaped = escapeForSwiftStringLiteral(apiPathPrefix)

        let components = document.components

        struct EndpointEntry {
            var method: String
            var fullPath: String
            var operationId: String
            var tags: [String]
            var security: [SpecSecurityRequirementEntry]?
            var parameters: [SpecParameter]?
            var responses: [SpecResponseRow]
        }

        let securitySchemeCatalog = securitySchemeEntries(from: components)

        var endpointEntries: [EndpointEntry] = []

        for route in document.routes {
            let routePath = route.path.rawValue
            let fullPath = apiPathPrefix + (routePath.hasPrefix("/") ? routePath : "/" + routePath)

            for endpoint in route.pathItem.endpoints {
                let operation = endpoint.operation
                guard let operationId = operation.operationId, !operationId.isEmpty else { continue }
                let method = endpoint.method.rawValue.uppercased()

                var responseRows: [SpecResponseRow] = []

                for (statusKey, responseRef) in operation.responses {
                    guard case .status(code: let code) = statusKey.value else { continue }
                    guard let response = components[responseRef] else { continue }

                    if let jsonContent = response.content[.json] {
                        responseRows.append(
                            contentsOf: specResponseRows(
                                statusCode: code,
                                jsonContent: jsonContent,
                                responseDescription: response.description,
                                components: components,
                                operationId: operationId
                            )
                        )
                    } else {
                        responseRows.append(SpecResponseRow(
                            statusCode: code,
                            responseMapKey: KawarimiExampleIds.defaultResponseMapKey,
                            mockExampleIdLiteral: "nil",
                            contentType: "application/json",
                            body: "{}",
                            responseDescription: response.description,
                            summaryLiteral: "nil"
                        ))
                    }
                }

                let tags = operation.tags ?? []
                let security = effectiveSecurityRequirementEntries(operation: operation, document: document)
                let parameters = OpenAPIParameterSpecSupport.specParameters(
                    pathItem: route.pathItem.parameters,
                    operation: operation.parameters,
                    components: components
                )

                endpointEntries.append(EndpointEntry(
                    method: method,
                    fullPath: fullPath,
                    operationId: operationId,
                    tags: tags,
                    security: security,
                    parameters: parameters,
                    responses: responseRows
                ))
            }
        }

        let descLiteral = description.map { "\"\(escapeForSwiftStringLiteral($0))\"" } ?? "nil"
        let serverURLEscaped = escapeForSwiftStringLiteral(serverURLString.isEmpty ? "https://example.com/api" : serverURLString)

        let endpointsLiteral = endpointEntries.map { entry in
            let responsesBlock = entry.responses.map { resp in
                let descVal = resp.responseDescription.map { "\"\(escapeForSwiftStringLiteral($0))\"" } ?? "nil"
                let bodyEsc = escapeForSwiftStringLiteral(resp.body)
                let ctEsc = escapeForSwiftStringLiteral(resp.contentType)
                return """
                        MockResponse(
                            statusCode: \(resp.statusCode),
                            contentType: "\(ctEsc)",
                            body: "\(bodyEsc)",
                            exampleId: \(resp.mockExampleIdLiteral),
                            summary: \(resp.summaryLiteral),
                            description: \(descVal)
                        ),
"""
            }.joined(separator: "\n")
            let tagsLiteral: String
            if entry.tags.isEmpty {
                tagsLiteral = "nil"
            } else {
                let tagStrings = entry.tags.map { "\"\(escapeForSwiftStringLiteral($0))\"" }.joined(separator: ", ")
                tagsLiteral = "[\(tagStrings)]"
            }
            let securityLiteral = endpointSecurityLiteral(entry.security)
            let parametersLiteral = endpointParametersLiteral(entry.parameters)
            return """
                    Endpoint(
                        path: "\(escapeForSwiftStringLiteral(entry.fullPath))",
                        method: HTTPRequest.Method("\(entry.method)")!,
                        operationId: "\(escapeForSwiftStringLiteral(entry.operationId))",
                        tags: \(tagsLiteral),
            \(securityLiteral)\(parametersLiteral)                        responses: [
            \(responsesBlock)
                        ]
                    ),
"""
        }.joined(separator: "\n")

        let responseMapLiteral = endpointEntries.map { entry in
            let byStatus = Dictionary(grouping: entry.responses, by: \.statusCode)
            let statusBlocks = byStatus.keys.sorted().map { code -> String in
                let rows = byStatus[code]!
                let innerPairs = rows.map { resp in
                    let mapKeyEsc = escapeForSwiftStringLiteral(resp.responseMapKey)
                    let bodyEsc = escapeForSwiftStringLiteral(resp.body)
                    let ctEsc = escapeForSwiftStringLiteral(resp.contentType)
                    return "\"\(mapKeyEsc)\": (body: \"\(bodyEsc)\", contentType: \"\(ctEsc)\")"
                }.joined(separator: ", ")
                return "\(code): [\(innerPairs)]"
            }.joined(separator: ", ")
            let key = "\(entry.method):\(entry.fullPath)"
            let keyEsc = escapeForSwiftStringLiteral(key)
            return "                \"\(keyEsc)\": [\(statusBlocks)],"
        }.joined(separator: "\n")

        let securitySchemesLiteral = securitySchemesPropertyLiteral(securitySchemeCatalog)

        return """
            // Generated by Kawarimi. Do not edit.

            import HTTPTypes
            import KawarimiCore

            public enum KawarimiSpec {
                public struct Meta: Codable, Sendable {
                    public var title: String
                    public var version: String
                    public var description: String?
                    public var serverURL: String
                    public var apiPathPrefix: String
                }
                public struct SecurityScheme: Codable, Sendable {
                    public var name: String
                    public var type: String
                    public var description: String?
                    public var apiKeyName: String?
                    public var apiKeyIn: String?
                    public var httpScheme: String?
                    public var bearerFormat: String?
                    public var openIdConnectURL: String?
                }
                public struct ScopedSecurityScheme: Codable, Sendable {
                    public var name: String
                    public var scopes: [String]?
                }
                public struct SecurityRequirement: Codable, Sendable {
                    public var schemes: [ScopedSecurityScheme]
                }
                public struct Endpoint: Codable, Sendable {
                    public var path: String
                    public var method: HTTPRequest.Method
                    public var operationId: String
                    public var tags: [String]?
                    public var security: [SecurityRequirement]?
                    public var parameters: [SpecParameter]?
                    public var responses: [MockResponse]
                }
                public struct MockResponse: Codable, Sendable {
                    public var statusCode: Int
                    public var contentType: String
                    public var body: String
                    public var exampleId: String?
                    public var summary: String?
                    public var description: String?
                }

                public static let meta = Meta(
                    title: "\(escapeForSwiftStringLiteral(title))",
                    version: "\(escapeForSwiftStringLiteral(version))",
                    description: \(descLiteral),
                    serverURL: "\(serverURLEscaped)",
                    apiPathPrefix: "\(apiPathPrefixEscaped)"
                )

            \(securitySchemesLiteral)

                public static let endpoints: [Endpoint] = [
            \(endpointsLiteral)
                ]

                public static let responseMap: [String: [Int: [String: (body: String, contentType: String)]]] = [
            \(responseMapLiteral)
                ]
            }

            extension KawarimiSpec.Meta: SpecMetaProviding {}
            extension KawarimiSpec.SecurityScheme: SpecSecuritySchemeProviding {}
            extension KawarimiSpec.ScopedSecurityScheme: SpecScopedSecuritySchemeProviding {}
            extension KawarimiSpec.SecurityRequirement: SpecSecurityRequirementProviding {
                public var schemeList: [any SpecScopedSecuritySchemeProviding] { schemes }
            }
            extension KawarimiSpec.MockResponse: SpecMockResponseProviding {}
            extension KawarimiSpec.Endpoint: SpecEndpointProviding {
                public var responseList: [any SpecMockResponseProviding] { responses }
            }

            public struct SpecResponse: Codable, Sendable {
                public var meta: KawarimiSpec.Meta
                public var endpoints: [KawarimiSpec.Endpoint]
                public var securitySchemes: [KawarimiSpec.SecurityScheme]?
                public init(
                    meta: KawarimiSpec.Meta,
                    endpoints: [KawarimiSpec.Endpoint],
                    securitySchemes: [KawarimiSpec.SecurityScheme]? = KawarimiSpec.securitySchemes
                ) {
                    self.meta = meta
                    self.endpoints = endpoints
                    self.securitySchemes = securitySchemes
                }
            }

            extension SpecResponse: KawarimiFetchedSpec {
                public var securitySchemeCatalog: [any SpecSecuritySchemeProviding]? {
                    guard let securitySchemes else { return nil }
                    return securitySchemes.map { $0 as any SpecSecuritySchemeProviding }
                }
            }
            """
    }

    private static func responseBodyJSON(
        content: OpenAPI.Content,
        components: OpenAPI.Components,
        operationId: String,
        statusCode: Int
    ) -> String {
        mockJSONBodyFromJSONMediaType(
            content: content,
            components: components,
            operationId: operationId,
            diagnosticPath: "responses.\(statusCode).content['application/json']"
        )
    }

    private static func swiftInitializerForSchema(
        _ schema: JSONSchema,
        components: OpenAPI.Components,
        operationId: String,
        diagnosticPath: String,
        namingStrategy: KawarimiNamingStrategy,
        handlerStubWarnings: inout [String],
        refChain: inout Set<OpenAPI.ComponentKey>
    ) throws -> String {
        if case .reference(let ref, _) = schema.value,
           let name = ref.name,
           let key = OpenAPI.ComponentKey(rawValue: name)
        {
            if refChain.contains(key) {
                throw KawarimiJutsuError.handlerGenerationUnsupported(
                    operationId: operationId,
                    detail:
                        "\(diagnosticPath) Circular JSON Schema $ref to components.schemas.\(name)."
                )
            }
            if let inner = components.schemas[key] {
                refChain.insert(key)
                defer { refChain.remove(key) }
                return try swiftInitializerForSchema(
                    inner,
                    components: components,
                    operationId: operationId,
                    diagnosticPath: diagnosticPath,
                    namingStrategy: namingStrategy,
                    handlerStubWarnings: &handlerStubWarnings,
                    refChain: &refChain
                )
            }
        }

        let resolved = schema

        switch resolved.value {
        case .all, .one, .any, .not:
            throw KawarimiJutsuError.handlerGenerationUnsupported(
                operationId: operationId,
                detail:
                    "Cannot generate stub initializers for allOf / oneOf / anyOf / not JSON Schema (\(diagnosticPath)). Simplify the schema or implement the `on…` closure manually."
            )
        case .reference, .boolean, .number, .integer, .string, .object, .array, .fragment, .null:
            break
        }

        if let allowed = resolved.allowedValues, !allowed.isEmpty {
            throw KawarimiJutsuError.handlerGenerationUnsupported(
                operationId: operationId,
                detail:
                    "Schema with enum (allowedValues) is not stubbed with string literals because swift-openapi-generator emits RawRepresentable etc. (\(diagnosticPath)). Remove the enum or implement the `on…` closure manually."
            )
        }

        if let objectContext = resolved.objectContext {
            let args = try objectContext.properties.map { name, propSchema -> String in
                let childPath = "\(diagnosticPath) · properties.\(name)"
                let valueExpr = try swiftInitializerForSchema(
                    propSchema,
                    components: components,
                    operationId: operationId,
                    diagnosticPath: childPath,
                    namingStrategy: namingStrategy,
                    handlerStubWarnings: &handlerStubWarnings,
                    refChain: &refChain
                )
                let swiftName = try namingStrategy.swiftMemberName(for: name)
                return "\(swiftName): \(valueExpr)"
            }
            return ".init(\(args.joined(separator: ", ")))"
        }

        if let arrayContext = resolved.arrayContext {
            guard let itemsSchema = arrayContext.items else { return "[]" }
            let itemPath = "\(diagnosticPath) · items"
            let itemExpr = try swiftInitializerForSchema(
                itemsSchema,
                components: components,
                operationId: operationId,
                diagnosticPath: itemPath,
                namingStrategy: namingStrategy,
                handlerStubWarnings: &handlerStubWarnings,
                refChain: &refChain
            )
            return "[\(itemExpr)]"
        }

        if OpenAPIDateMockSupport.isOpenAPIAbsoluteDateStringSchema(resolved) {
            return OpenAPIDateMockSupport.swiftDateLiteralForDateSchema(
                resolved: resolved,
                operationId: operationId,
                diagnosticPath: diagnosticPath,
                handlerStubWarnings: &handlerStubWarnings
            )
        }

        if let swiftLiteral = exampleToSwiftLiteral(schemaPrimaryExample(resolved), jsonType: resolved.jsonType) {
            return swiftLiteral
        }
        switch resolved.jsonType {
        case .some(.string): return "\"\""
        case .some(.integer): return "0"
        case .some(.number): return "0.0"
        case .some(.boolean): return "false"
        default: return "\"\""
        }
    }

    private static func exampleToSwiftLiteral(_ example: AnyCodable?, jsonType: JSONType?) -> String? {
        guard let example else { return nil }
        guard let data = try? JSONEncoder().encode(example) else { return nil }
        switch jsonType {
        case .string:
            guard let s = try? JSONDecoder().decode(String.self, from: data) else { return nil }
            return "\"\(escapeForSwiftStringLiteral(s))\""
        case .integer:
            guard let i = try? JSONDecoder().decode(Int.self, from: data) else { return nil }
            return "\(i)"
        case .number:
            guard let d = try? JSONDecoder().decode(Double.self, from: data) else { return nil }
            return "\(d)"
        case .boolean:
            guard let b = try? JSONDecoder().decode(Bool.self, from: data) else { return nil }
            return b ? "true" : "false"
        default:
            return nil
        }
    }
}
