import Foundation
import KawarimiCore
import OpenAPIKit30
import Yams

public enum KawarimiJutsu {
    public static func loadOpenAPISpec(path: String) throws -> OpenAPI.Document {
        guard let data = FileManager.default.contents(atPath: path) else {
            throw KawarimiJutsuError.specFileNotFound(path: path)
        }
        guard let content = String(data: data, encoding: .utf8) else {
            throw KawarimiJutsuError.specFileInvalidEncoding
        }
        do {
            return try YAMLDecoder().decode(OpenAPI.Document.self, from: content)
        } catch {
            throw KawarimiJutsuError.specParseError(String(describing: error))
        }
    }

    public static func generateSwiftSource(document: OpenAPI.Document) -> String {
        let cases = generateTransportCases(document: document)
        return """
            // Generated by Kawarimi. Do not edit.

            import Foundation
            import OpenAPIRuntime
            import HTTPTypes

            public struct Kawarimi: ClientTransport {
                public init() {}
                public func send(_ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String) async throws -> (HTTPResponse, HTTPBody?) {
                    switch operationID {
            \(cases)
                    default:
                        return (HTTPResponse(status: .notFound), nil)
                    }
                }
            }
            """
    }

    // MARK: - Mock transport generation

    private static func generateTransportCases(document: OpenAPI.Document) -> String {
        var lines: [String] = []
        let components = document.components

        for route in document.routes {
            for endpoint in route.pathItem.endpoints {
                let operation = endpoint.operation
                guard let operationId = operation.operationId, !operationId.isEmpty else { continue }

                let jsonBody = defaultResponseJSON(operation: operation, components: components)
                let escaped = escapeForSwiftStringLiteral(jsonBody)
                lines.append("                    case \"\(operationId)\":")
                lines.append("                        return (HTTPResponse(status: .ok), HTTPBody(\"\(escaped)\"))")
            }
        }
        return lines.joined(separator: "\n")
    }

    private static func escapeForSwiftStringLiteral(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
    }

    private static func defaultResponseJSON(operation: OpenAPI.Operation, components: OpenAPI.Components) -> String {
        guard let responseEither = operation.responses[status: 200],
              let response = components[responseEither],
              let content = response.content[.json] else {
            return "{}"
        }
        return mockJSONBodyFromJSONMediaType(content: content, components: components)
    }

    private static func mockJSONBodyFromJSONMediaType(content: OpenAPI.Content, components: OpenAPI.Components) -> String {
        if let exampleJSON = exampleToJSONString(content.example) {
            return exampleJSON
        }
        guard let schemaEither = content.schema else { return "{}" }
        switch schemaEither {
        case .a(let ref):
            guard let name = ref.name,
                  let key = OpenAPI.ComponentKey(rawValue: name),
                  let schema = components.schemas[key] else {
                return "{}"
            }
            return defaultJSONForSchema(schema, components: components)
        case .b(let schema):
            return defaultJSONForSchema(schema, components: components)
        }
    }

    private static func resolveSchema(_ schema: JSONSchema, components: OpenAPI.Components) -> JSONSchema? {
        guard case .reference(let ref, _) = schema.value,
              let name = ref.name,
              let key = OpenAPI.ComponentKey(rawValue: name) else {
            return schema
        }
        return components.schemas[key]
    }

    private static func defaultJSONForSchema(_ schema: JSONSchema, components: OpenAPI.Components) -> String {
        let resolved = resolveSchema(schema, components: components) ?? schema

        if let exampleJSON = exampleToJSONString(resolved.example) {
            return exampleJSON
        }
        if let defaultJSON = exampleToJSONString(resolved.defaultValue) {
            return defaultJSON
        }

        if let objectContext = resolved.objectContext {
            let pairs = objectContext.properties.map { name, propSchema -> String in
                let value = defaultJSONForSchema(propSchema, components: components)
                return "\"\(name)\": \(value)"
            }
            return "{\(pairs.joined(separator: ", "))}"
        }

        if let arrayContext = resolved.arrayContext {
            guard let itemsSchema = arrayContext.items else {
                return "[]"
            }
            let resolvedItem = resolveSchema(itemsSchema, components: components) ?? itemsSchema
            let itemJSON = defaultJSONForSchema(resolvedItem, components: components)
            return "[\(itemJSON)]"
        }

        switch resolved.value {
        case .one(of: let schemas, core: _), .any(of: let schemas, core: _):
            for sub in schemas {
                let j = defaultJSONForSchema(sub, components: components)
                if !isVacuousJSONMock(j) { return j }
            }
            if let first = schemas.first {
                return defaultJSONForSchema(first, components: components)
            }
            return "{}"
        case .all(of: let schemas, core: _):
            if let first = schemas.first {
                return defaultJSONForSchema(first, components: components)
            }
            return "{}"
        case .not:
            return "{}"
        default:
            break
        }

        if let allowed = resolved.allowedValues, let first = allowed.first,
           let j = exampleToJSONString(first) {
            return j
        }

        switch resolved.jsonType {
        case .some(.string): return "\"\""
        case .some(.integer): return "0"
        case .some(.number): return "0.0"
        case .some(.boolean): return "false"
        default: return "{}"
        }
    }

    /// True for placeholder-shaped JSON when probing oneOf branches or object composition.
    private static func isVacuousJSONMock(_ json: String) -> Bool {
        let t = json.trimmingCharacters(in: .whitespacesAndNewlines)
        switch t {
        case "{}", "\"\"", "0", "0.0", "false", "[]": return true
        default: return false
        }
    }

    private static func exampleToJSONString(_ example: AnyCodable?) -> String? {
        guard let example else { return nil }
        guard let data = try? JSONEncoder().encode(example),
              let s = String(data: data, encoding: .utf8) else { return nil }
        return s
    }

    public static func generateKawarimiHandlerSource(
        document: OpenAPI.Document,
        namingStrategy: KawarimiNamingStrategy = KawarimiGeneratorConfigYAML.defaults.namingStrategy,
        accessModifier: KawarimiAccessModifier = KawarimiGeneratorConfigYAML.defaults.accessModifier,
        handlerStubPolicy: KawarimiHandlerStubPolicy = KawarimiGeneratorConfigYAML.defaults.handlerStubPolicy
    ) throws -> (source: String, warnings: [String]) {
        let (methods, warnings, fatalErrorStubIndex) = try generateHandlerMethods(
            document: document,
            namingStrategy: namingStrategy,
            accessKeyword: accessModifier.swiftKeyword,
            handlerStubPolicy: handlerStubPolicy
        )
        var allWarnings = warnings
        if !fatalErrorStubIndex.isEmpty {
            allWarnings.append(
                stderrSummaryForFatalErrorStubs(operationIds: fatalErrorStubIndex.map(\.operationId))
            )
        }
        let indexComment = fatalErrorStubSourceCommentBlock(entries: fatalErrorStubIndex)
        let source = """
            // Generated by Kawarimi. Do not edit.\(indexComment)

            import Foundation
            import OpenAPIRuntime
            import HTTPTypes

            public struct KawarimiHandler: APIProtocol {
                public init() {}
            \(methods)
            }
            """
        return (source, allWarnings)
    }

    private static func handlerWitnessPropertyName(methodName: String) -> String {
        guard let first = methodName.first else { return "onOperation" }
        return "on" + String(first).uppercased() + methodName.dropFirst()
    }

    private static func openapiOperationContextLabel(routePath: String, httpMethod: String) -> String {
        "[\(httpMethod.uppercased()) \(routePath)] "
    }

    private static func stubClosureBodyLines(stub: HandlerOutputStub) -> [String] {
        switch stub {
        case .okJSON(let expr):
            return ["        return .ok(.init(body: .json(\(expr))))"]
        case .okJSONDecoded(let payloadTypeName, let jsonLiteralEscaped):
            return [
                "        let _kawarimiStubData = Data(\"\(jsonLiteralEscaped)\".utf8)",
                "        let _kawarimiDecodedBody = try JSONDecoder().decode(\(payloadTypeName).self, from: _kawarimiStubData)",
                "        return .ok(.init(body: .json(_kawarimiDecodedBody)))",
            ]
        case .okEmpty:
            return ["        return .ok(.init())"]
        case .createdJSON(let expr):
            return ["        return .created(.init(body: .json(\(expr))))"]
        case .createdJSONDecoded(let payloadTypeName, let jsonLiteralEscaped):
            return [
                "        let _kawarimiStubData = Data(\"\(jsonLiteralEscaped)\".utf8)",
                "        let _kawarimiDecodedBody = try JSONDecoder().decode(\(payloadTypeName).self, from: _kawarimiStubData)",
                "        return .created(.init(body: .json(_kawarimiDecodedBody)))",
            ]
        case .createdEmpty:
            return ["        return .created(.init())"]
        case .noContent:
            return ["        return .noContent(.init())"]
        case .unsupportedFatalError(let operationId, let detail):
            let msg =
                "Kawarimi: KawarimiHandler stub unsupported (operationId: \(operationId)): \(detail)"
            let escaped = escapeForSwiftStringLiteral(msg)
            return ["        fatalError(\"\(escaped)\")"]
        }
    }

    private static func stderrWarningForFatalErrorStub(operationId: String, detail: String) -> String {
        "Kawarimi warning: KawarimiHandler: using fatalError() stub for operationId \(operationId); \(detail) Use handlerStubPolicy: throw or omit the key (fail-fast default since 0.7) to fail generation instead."
    }

    /// Safe for `// …` lines (no `*/`, no newlines).
    private static func sanitizeForSourceCommentLine(_ s: String) -> String {
        s.replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\r", with: " ")
            .replacingOccurrences(of: "*/", with: "* /")
    }

    private static func fatalErrorStubSourceCommentBlock(entries: [(operationId: String, routeLabel: String)]) -> String {
        guard !entries.isEmpty else { return "" }
        var lines: [String] = [
            "",
            "// Kawarimi: handlerStubPolicy fatalError — operations below use fatalError() stub bodies.",
            "//   Override with the matching on… closure, or use handlerStubPolicy: throw (or omit; default) to fail at codegen.",
        ]
        for e in entries {
            let id = sanitizeForSourceCommentLine(e.operationId)
            let label = sanitizeForSourceCommentLine(e.routeLabel)
            lines.append("//   \(label) \(id)")
        }
        return lines.joined(separator: "\n")
    }

    private static func stderrSummaryForFatalErrorStubs(operationIds: [String]) -> String {
        let n = operationIds.count
        let noun = n == 1 ? "operation" : "operations"
        let list = operationIds.map { sanitizeForSourceCommentLine($0) }.joined(separator: ", ")
        return "Kawarimi warning: Summary: \(n) \(noun) use fatalError stubs: \(list)"
    }

    private static func generateHandlerMethods(
        document: OpenAPI.Document,
        namingStrategy: KawarimiNamingStrategy,
        accessKeyword: String,
        handlerStubPolicy: KawarimiHandlerStubPolicy
    ) throws -> (String, [String], [(operationId: String, routeLabel: String)]) {
        var lines: [String] = []
        var warnings: [String] = []
        var fatalErrorStubIndex: [(operationId: String, routeLabel: String)] = []
        let components = document.components

        for route in document.routes {
            let routePath = route.path.rawValue
            for endpoint in route.pathItem.endpoints {
                let operation = endpoint.operation
                guard let operationId = operation.operationId, !operationId.isEmpty else { continue }
                let httpMethod = endpoint.method.rawValue
                let opContext = openapiOperationContextLabel(routePath: routePath, httpMethod: httpMethod)
                let typeName = try namingStrategy.swiftOperationTypeName(forOperationId: operationId)
                let methodName = try namingStrategy.swiftOperationMethodName(forOperationId: operationId)
                let witnessName = handlerWitnessPropertyName(methodName: methodName)
                let inputType = "Operations.\(typeName).Input"
                let outputType = "Operations.\(typeName).Output"
                let stub: HandlerOutputStub
                switch handlerStubPolicy {
                case .throw:
                    stub = try selectHandlerStubResponse(
                        operation: operation,
                        components: components,
                        operationId: operationId,
                        operationContext: opContext,
                        operationSwiftTypeName: typeName
                    )
                case .fatalError:
                    do {
                        stub = try selectHandlerStubResponse(
                            operation: operation,
                            components: components,
                            operationId: operationId,
                            operationContext: opContext,
                            operationSwiftTypeName: typeName
                        )
                    } catch let error as KawarimiJutsuError {
                        guard case .handlerGenerationUnsupported(_, let detail) = error else { throw error }
                        warnings.append(stderrWarningForFatalErrorStub(operationId: operationId, detail: detail))
                        let label = opContext.trimmingCharacters(in: .whitespaces)
                        fatalErrorStubIndex.append((operationId: operationId, routeLabel: label))
                        stub = .unsupportedFatalError(operationId: operationId, detail: detail)
                    }
                }
                lines.append(
                    "    \(accessKeyword) var \(witnessName): @Sendable (\(inputType)) async throws -> \(outputType) = { _ in"
                )
                lines.append(contentsOf: stubClosureBodyLines(stub: stub))
                lines.append("    }")
                lines.append("    \(accessKeyword) func \(methodName)(_ input: \(inputType)) async throws -> \(outputType) {")
                lines.append("        try await \(witnessName)(input)")
                lines.append("    }")
            }
        }
        return (lines.joined(separator: "\n"), warnings, fatalErrorStubIndex)
    }

    private enum HandlerOutputStub {
        case okJSON(String)
        case okJSONDecoded(payloadTypeName: String, jsonLiteralEscaped: String)
        case okEmpty
        case createdJSON(String)
        case createdJSONDecoded(payloadTypeName: String, jsonLiteralEscaped: String)
        case createdEmpty
        case noContent
        case unsupportedFatalError(operationId: String, detail: String)
    }

    private static func selectHandlerStubResponse(
        operation: OpenAPI.Operation,
        components: OpenAPI.Components,
        operationId: String,
        operationContext: String,
        operationSwiftTypeName: String
    ) throws -> HandlerOutputStub {
        for code in [200, 201] {
            let statusCode = OpenAPI.Response.StatusCode.status(code: code)
            guard let responseEither = operation.responses[status: statusCode],
                  let response = components[responseEither] else { continue }

            if let content = response.content[.json] {
                let initializerExpr: String?
                do {
                    initializerExpr = try bodyExprForResponse(
                        response: response,
                        components: components,
                        operationId: operationId,
                        operationContext: operationContext,
                        httpStatus: code
                    )
                } catch {
                    initializerExpr = nil
                }
                if let expr = initializerExpr {
                    return code == 200 ? .okJSON(expr) : .createdJSON(expr)
                }
                let json = mockJSONBodyFromJSONMediaType(content: content, components: components)
                let escaped = escapeForSwiftStringLiteral(json)
                let payloadType = handlerStubJSONPayloadSwiftType(
                    operationSwiftTypeName: operationSwiftTypeName,
                    httpStatus: code,
                    content: content
                )
                return code == 200
                    ? .okJSONDecoded(payloadTypeName: payloadType, jsonLiteralEscaped: escaped)
                    : .createdJSONDecoded(payloadTypeName: payloadType, jsonLiteralEscaped: escaped)
            }

            if response.content.isEmpty {
                if let headers = response.headers, !headers.isEmpty {
                    throw KawarimiJutsuError.handlerGenerationUnsupported(
                        operationId: operationId,
                        detail:
                            "\(operationContext)HTTP \(code) declares response headers but no body. Cannot emit stub initializers automatically; implement the `on…` closure manually or adjust the headers."
                    )
                }
                return code == 200 ? .okEmpty : .createdEmpty
            }

            throw KawarimiJutsuError.handlerGenerationUnsupported(
                operationId: operationId,
                detail:
                    "\(operationContext)HTTP \(code) includes non-JSON content. Kawarimi only stubs 200/201 with a JSON body or without content."
            )
        }
        if operation.responses[status: OpenAPI.Response.StatusCode.status(code: 204)] != nil {
            return .noContent
        }
        throw KawarimiJutsuError.handlerGenerationUnsupported(
            operationId: operationId,
            detail:
                "\(operationContext)Requires HTTP 200 / 201 (JSON or no content) or 204. Only stubs aligned with swift-openapi-generator Operations output are generated."
        )
    }

    private static func bodyExprForResponse(
        response: OpenAPI.Response,
        components: OpenAPI.Components,
        operationId: String,
        operationContext: String,
        httpStatus: Int
    ) throws -> String? {
        guard let content = response.content[.json] else { return nil }
        guard let schema = resolveSchemaFromContent(content: content, components: components) else { return nil }
        let schemaHint = schemaDiagnosticHint(content: content, components: components)
        let path =
            "\(operationContext)OpenAPI JSON path: paths · … · responses.\(httpStatus).content['application/json'].schema\(schemaHint.map { " → \($0)" } ?? "")"
        return try swiftInitializerForSchema(
            schema,
            components: components,
            operationId: operationId,
            diagnosticPath: path
        )
    }

    private static func schemaDiagnosticHint(content: OpenAPI.Content, components: OpenAPI.Components) -> String? {
        guard let schemaEither = content.schema else { return nil }
        switch schemaEither {
        case .a(let ref):
            return ref.name.map { "components.schemas.\($0)" }
        case .b:
            return nil
        }
    }

    private static func resolveSchemaFromContent(content: OpenAPI.Content, components: OpenAPI.Components) -> JSONSchema? {
        guard let schemaEither = content.schema else { return nil }
        switch schemaEither {
        case .a(let ref):
            return components[ref]
        case .b(let schema):
            return schema
        }
    }

    /// Swift type passed to `JSONDecoder` for `application/json` bodies, aligned with swift-openapi-generator.
    private static func handlerStubJSONPayloadSwiftType(
        operationSwiftTypeName: String,
        httpStatus: Int,
        content: OpenAPI.Content
    ) -> String {
        let outputCase = httpStatus == 201 ? "Created" : "Ok"
        let jsonPayload = "Operations.\(operationSwiftTypeName).Output.\(outputCase).Body.jsonPayload"
        guard let schemaEither = content.schema else { return jsonPayload }
        switch schemaEither {
        case .a(let ref):
            if let name = ref.name {
                return "Components.Schemas.\(name)"
            }
            return jsonPayload
        case .b:
            return jsonPayload
        }
    }

    private static func pathPrefix(in document: OpenAPI.Document) -> String {
        guard let raw = document.servers.first?.urlTemplate.rawValue, !raw.isEmpty,
              let url = URL(string: raw) else {
            return ""
        }
        let path = url.path
        if path.isEmpty || path == "/" {
            return ""
        }
        return KawarimiPath.joinPathPrefix(KawarimiPath.splitPathSegments(path))
    }

    // MARK: - KawarimiSpec source emission

    private struct NamedJSONExample {
        let mapKey: String
        let json: String
        let summary: String?
    }

    private struct SpecResponseRow {
        var statusCode: Int
        var responseMapKey: String
        var mockExampleIdLiteral: String
        var contentType: String
        var body: String
        var responseDescription: String?
        var summaryLiteral: String
    }

    /// OpenAPI `examples` map entries with inline JSON values (skips `externalValue`).
    private static func namedJSONExamples(from content: OpenAPI.Content, components: OpenAPI.Components) -> [NamedJSONExample]? {
        guard let map = content.examples, !map.isEmpty else { return nil }
        var out: [NamedJSONExample] = []
        for (name, either) in map {
            guard let example = components[either] else { continue }
            guard case let .b(value)? = example.value else { continue }
            guard let json = exampleToJSONString(value) else { continue }
            out.append(NamedJSONExample(mapKey: name, json: json, summary: example.summary))
        }
        if out.isEmpty { return nil }
        out.sort { $0.mapKey < $1.mapKey }
        return out
    }

    private static func specResponseRows(
        statusCode: Int,
        jsonContent: OpenAPI.Content,
        responseDescription: String?,
        components: OpenAPI.Components
    ) -> [SpecResponseRow] {
        if let named = namedJSONExamples(from: jsonContent, components: components), !named.isEmpty {
            return named.map { item in
                let idLit = "\"\(escapeForSwiftStringLiteral(item.mapKey))\""
                let summ = item.summary.map { "\"\(escapeForSwiftStringLiteral($0))\"" } ?? "nil"
                return SpecResponseRow(
                    statusCode: statusCode,
                    responseMapKey: item.mapKey,
                    mockExampleIdLiteral: idLit,
                    contentType: "application/json",
                    body: item.json,
                    responseDescription: responseDescription,
                    summaryLiteral: summ
                )
            }
        }
        let body = responseBodyJSON(content: jsonContent, components: components)
        return [SpecResponseRow(
            statusCode: statusCode,
            responseMapKey: KawarimiExampleIds.defaultResponseMapKey,
            mockExampleIdLiteral: "nil",
            contentType: "application/json",
            body: body,
            responseDescription: responseDescription,
            summaryLiteral: "nil"
        )]
    }

    public static func generateKawarimiSpecSource(document: OpenAPI.Document) -> String {
        let info = document.info
        let title = info.title
        let version = info.version
        let description = info.description

        let serverURLString = document.servers.first?.urlTemplate.rawValue ?? ""
        let apiPathPrefix = pathPrefix(in: document)
        let apiPathPrefixEscaped = escapeForSwiftStringLiteral(apiPathPrefix)

        let components = document.components

        struct EndpointEntry {
            var method: String
            var fullPath: String
            var operationId: String
            var responses: [SpecResponseRow]
        }

        var endpointEntries: [EndpointEntry] = []

        for route in document.routes {
            let routePath = route.path.rawValue
            let fullPath = apiPathPrefix + (routePath.hasPrefix("/") ? routePath : "/" + routePath)

            for endpoint in route.pathItem.endpoints {
                let operation = endpoint.operation
                guard let operationId = operation.operationId, !operationId.isEmpty else { continue }
                let method = endpoint.method.rawValue.uppercased()

                var responseRows: [SpecResponseRow] = []

                for (statusKey, responseRef) in operation.responses {
                    guard case .status(code: let code) = statusKey.value else { continue }
                    guard let response = components[responseRef] else { continue }

                    if let jsonContent = response.content[.json] {
                        responseRows.append(
                            contentsOf: specResponseRows(
                                statusCode: code,
                                jsonContent: jsonContent,
                                responseDescription: response.description,
                                components: components
                            )
                        )
                    } else {
                        responseRows.append(SpecResponseRow(
                            statusCode: code,
                            responseMapKey: KawarimiExampleIds.defaultResponseMapKey,
                            mockExampleIdLiteral: "nil",
                            contentType: "application/json",
                            body: "{}",
                            responseDescription: response.description,
                            summaryLiteral: "nil"
                        ))
                    }
                }

                endpointEntries.append(EndpointEntry(
                    method: method,
                    fullPath: fullPath,
                    operationId: operationId,
                    responses: responseRows
                ))
            }
        }

        let descLiteral = description.map { "\"\(escapeForSwiftStringLiteral($0))\"" } ?? "nil"
        let serverURLEscaped = escapeForSwiftStringLiteral(serverURLString.isEmpty ? "https://example.com/api" : serverURLString)

        let endpointsLiteral = endpointEntries.map { entry in
            let responsesBlock = entry.responses.map { resp in
                let descVal = resp.responseDescription.map { "\"\(escapeForSwiftStringLiteral($0))\"" } ?? "nil"
                let bodyEsc = escapeForSwiftStringLiteral(resp.body)
                let ctEsc = escapeForSwiftStringLiteral(resp.contentType)
                return """
                        MockResponse(
                            statusCode: \(resp.statusCode),
                            contentType: "\(ctEsc)",
                            body: "\(bodyEsc)",
                            exampleId: \(resp.mockExampleIdLiteral),
                            summary: \(resp.summaryLiteral),
                            description: \(descVal)
                        ),
"""
            }.joined(separator: "\n")
            return """
                    Endpoint(
                        path: "\(escapeForSwiftStringLiteral(entry.fullPath))",
                        method: HTTPRequest.Method("\(entry.method)")!,
                        operationId: "\(escapeForSwiftStringLiteral(entry.operationId))",
                        responses: [
            \(responsesBlock)
                        ]
                    ),
"""
        }.joined(separator: "\n")

        let responseMapLiteral = endpointEntries.map { entry in
            let byStatus = Dictionary(grouping: entry.responses, by: \.statusCode)
            let statusBlocks = byStatus.keys.sorted().map { code -> String in
                let rows = byStatus[code]!
                let innerPairs = rows.map { resp in
                    let mapKeyEsc = escapeForSwiftStringLiteral(resp.responseMapKey)
                    let bodyEsc = escapeForSwiftStringLiteral(resp.body)
                    let ctEsc = escapeForSwiftStringLiteral(resp.contentType)
                    return "\"\(mapKeyEsc)\": (body: \"\(bodyEsc)\", contentType: \"\(ctEsc)\")"
                }.joined(separator: ", ")
                return "\(code): [\(innerPairs)]"
            }.joined(separator: ", ")
            let key = "\(entry.method):\(entry.fullPath)"
            let keyEsc = escapeForSwiftStringLiteral(key)
            return "                \"\(keyEsc)\": [\(statusBlocks)],"
        }.joined(separator: "\n")

        return """
            // Generated by Kawarimi. Do not edit.

            import HTTPTypes
            import KawarimiCore

            public enum KawarimiSpec {
                public struct Meta: Codable, Sendable {
                    public var title: String
                    public var version: String
                    public var description: String?
                    public var serverURL: String
                    public var apiPathPrefix: String
                }
                public struct Endpoint: Codable, Sendable {
                    public var path: String
                    public var method: HTTPRequest.Method
                    public var operationId: String
                    public var responses: [MockResponse]
                }
                public struct MockResponse: Codable, Sendable {
                    public var statusCode: Int
                    public var contentType: String
                    public var body: String
                    public var exampleId: String?
                    public var summary: String?
                    public var description: String?
                }

                public static let meta = Meta(
                    title: "\(escapeForSwiftStringLiteral(title))",
                    version: "\(escapeForSwiftStringLiteral(version))",
                    description: \(descLiteral),
                    serverURL: "\(serverURLEscaped)",
                    apiPathPrefix: "\(apiPathPrefixEscaped)"
                )

                public static let endpoints: [Endpoint] = [
            \(endpointsLiteral)
                ]

                public static let responseMap: [String: [Int: [String: (body: String, contentType: String)]]] = [
            \(responseMapLiteral)
                ]
            }

            extension KawarimiSpec.Meta: SpecMetaProviding {}
            extension KawarimiSpec.MockResponse: SpecMockResponseProviding {}
            extension KawarimiSpec.Endpoint: SpecEndpointProviding {
                public var responseList: [any SpecMockResponseProviding] { responses }
            }

            public struct SpecResponse: Codable, Sendable {
                public var meta: KawarimiSpec.Meta
                public var endpoints: [KawarimiSpec.Endpoint]
                public init(meta: KawarimiSpec.Meta, endpoints: [KawarimiSpec.Endpoint]) {
                    self.meta = meta
                    self.endpoints = endpoints
                }
            }

            extension SpecResponse: KawarimiFetchedSpec {}
            """
    }

    private static func responseBodyJSON(content: OpenAPI.Content, components: OpenAPI.Components) -> String {
        mockJSONBodyFromJSONMediaType(content: content, components: components)
    }

    private static func swiftInitializerForSchema(
        _ schema: JSONSchema,
        components: OpenAPI.Components,
        operationId: String,
        diagnosticPath: String
    ) throws -> String {
        let resolved = resolveSchema(schema, components: components) ?? schema

        switch resolved.value {
        case .all, .one, .any, .not:
            throw KawarimiJutsuError.handlerGenerationUnsupported(
                operationId: operationId,
                detail:
                    "Cannot generate stub initializers for allOf / oneOf / anyOf / not JSON Schema (\(diagnosticPath)). Simplify the schema or implement the `on…` closure manually."
            )
        case .reference, .boolean, .number, .integer, .string, .object, .array, .fragment:
            break
        }

        if let allowed = resolved.allowedValues, !allowed.isEmpty {
            throw KawarimiJutsuError.handlerGenerationUnsupported(
                operationId: operationId,
                detail:
                    "Schema with enum (allowedValues) is not stubbed with string literals because swift-openapi-generator emits RawRepresentable etc. (\(diagnosticPath)). Remove the enum or implement the `on…` closure manually."
            )
        }

        if let objectContext = resolved.objectContext {
            let args = try objectContext.properties.map { name, propSchema -> String in
                let childPath = "\(diagnosticPath) · properties.\(name)"
                let valueExpr = try swiftInitializerForSchema(
                    propSchema,
                    components: components,
                    operationId: operationId,
                    diagnosticPath: childPath
                )
                return "\(name): \(valueExpr)"
            }
            return ".init(\(args.joined(separator: ", ")))"
        }

        if let arrayContext = resolved.arrayContext {
            guard let itemsSchema = arrayContext.items else { return "[]" }
            let itemPath = "\(diagnosticPath) · items"
            let itemExpr = try swiftInitializerForSchema(
                resolveSchema(itemsSchema, components: components) ?? itemsSchema,
                components: components,
                operationId: operationId,
                diagnosticPath: itemPath
            )
            return "[\(itemExpr)]"
        }

        if let swiftLiteral = exampleToSwiftLiteral(resolved.example, jsonType: resolved.jsonType) {
            return swiftLiteral
        }
        switch resolved.jsonType {
        case .some(.string): return "\"\""
        case .some(.integer): return "0"
        case .some(.number): return "0.0"
        case .some(.boolean): return "false"
        default: return "\"\""
        }
    }

    private static func exampleToSwiftLiteral(_ example: AnyCodable?, jsonType: JSONType?) -> String? {
        guard let example else { return nil }
        guard let data = try? JSONEncoder().encode(example) else { return nil }
        switch jsonType {
        case .string:
            guard let s = try? JSONDecoder().decode(String.self, from: data) else { return nil }
            return "\"\(escapeForSwiftStringLiteral(s))\""
        case .integer:
            guard let i = try? JSONDecoder().decode(Int.self, from: data) else { return nil }
            return "\(i)"
        case .number:
            guard let d = try? JSONDecoder().decode(Double.self, from: data) else { return nil }
            return "\(d)"
        case .boolean:
            guard let b = try? JSONDecoder().decode(Bool.self, from: data) else { return nil }
            return b ? "true" : "false"
        default:
            return nil
        }
    }
}
