import Foundation
import OpenAPIKit30
import Yams

/// OpenAPI のパースとモック・ハンドラ用 Swift ソース生成。
public enum KawarimiJutsu {
    public static func loadOpenAPISpec(path: String) throws -> OpenAPI.Document {
        guard let data = FileManager.default.contents(atPath: path) else {
            throw KawarimiJutsuError.specFileNotFound(path: path)
        }
        guard let content = String(data: data, encoding: .utf8) else {
            throw KawarimiJutsuError.specFileInvalidEncoding
        }
        do {
            return try YAMLDecoder().decode(OpenAPI.Document.self, from: content)
        } catch {
            throw KawarimiJutsuError.specParseError(String(describing: error))
        }
    }

    public static func generateSwiftSource(document: OpenAPI.Document) -> String {
        let cases = generateTransportCases(document: document)
        return """
            // Generated by Kawarimi. Do not edit.

            import Foundation
            import OpenAPIRuntime
            import HTTPTypes

            public struct Kawarimi: ClientTransport {
                public init() {}
                public func send(_ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String) async throws -> (HTTPResponse, HTTPBody?) {
                    switch operationID {
            \(cases)
                    default:
                        return (HTTPResponse(status: .notFound), nil)
                    }
                }
            }
            """
    }

    // MARK: - モック生成の内部

    private static func generateTransportCases(document: OpenAPI.Document) -> String {
        var lines: [String] = []
        let components = document.components

        for route in document.routes {
            for endpoint in route.pathItem.endpoints {
                let operation = endpoint.operation
                guard let operationId = operation.operationId, !operationId.isEmpty else { continue }

                let jsonBody = defaultResponseJSON(operation: operation, components: components)
                let escaped = escapeForSwiftStringLiteral(jsonBody)
                lines.append("                    case \"\(operationId)\":")
                lines.append("                        return (HTTPResponse(status: .ok), HTTPBody(\"\(escaped)\"))")
            }
        }
        return lines.joined(separator: "\n")
    }

    private static func escapeForSwiftStringLiteral(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
    }

    /// ビルド時警告を stderr に出力（プラグイン実行コンテキストで使用）
    private static func warnToStderr(_ message: String) {
        let line = message + "\n"
        if let data = line.data(using: .utf8) {
            try? FileHandle.standardError.write(contentsOf: data)
        }
    }

    private static func defaultResponseJSON(operation: OpenAPI.Operation, components: OpenAPI.Components) -> String {
        guard let responseEither = operation.responses[status: 200],
              let response = components[responseEither],
              let content = response.content[.json],
              let schemaEither = content.schema else {
            return "{}"
        }
        guard let ref = schemaEither.reference,
              let name = ref.name,
              let key = OpenAPI.ComponentKey(rawValue: name),
              let schema = components.schemas[key] else {
            return "{}"
        }
        return defaultJSONForSchema(schema, components: components)
    }

    private static func resolveSchema(_ schema: JSONSchema, components: OpenAPI.Components) -> JSONSchema? {
        guard case .reference(let ref, _) = schema.value,
              let name = ref.name,
              let key = OpenAPI.ComponentKey(rawValue: name) else {
            return schema
        }
        return components.schemas[key]
    }

    private static func defaultJSONForSchema(_ schema: JSONSchema, components: OpenAPI.Components) -> String {
        let resolved = resolveSchema(schema, components: components) ?? schema

        if let objectContext = resolved.objectContext {
            let pairs = objectContext.properties.map { name, propSchema -> String in
                let value = defaultJSONForSchema(propSchema, components: components)
                return "\"\(name)\": \(value)"
            }
            return "{\(pairs.joined(separator: ", "))}"
        }

        if let arrayContext = resolved.arrayContext {
            guard let itemsSchema = arrayContext.items else {
                return "[]"
            }
            let resolvedItem = resolveSchema(itemsSchema, components: components) ?? itemsSchema
            let itemJSON = defaultJSONForSchema(resolvedItem, components: components)
            return "[\(itemJSON)]"
        }

        if let exampleJSON = exampleToJSONString(resolved.example) {
            return exampleJSON
        }
        switch resolved.jsonType {
        case .some(.string): return "\"\""
        case .some(.integer): return "0"
        case .some(.number): return "0.0"
        case .some(.boolean): return "false"
        default: return "\"\""
        }
    }

    private static func exampleToJSONString(_ example: AnyCodable?) -> String? {
        guard let example else { return nil }
        guard let data = try? JSONEncoder().encode(example),
              let s = String(data: data, encoding: .utf8) else { return nil }
        return s
    }

    public static func generateKawarimiHandlerSource(document: OpenAPI.Document) -> String {
        let methods = generateHandlerMethods(document: document)
        return """
            // Generated by Kawarimi. Do not edit.

            import Foundation
            import OpenAPIRuntime
            import HTTPTypes

            public struct KawarimiHandler: APIProtocol {
                public init() {}
            \(methods)
            }
            """
    }

    private static func generateHandlerMethods(document: OpenAPI.Document) -> String {
        var lines: [String] = []
        let components = document.components

        for route in document.routes {
            for endpoint in route.pathItem.endpoints {
                let operation = endpoint.operation
                guard let operationId = operation.operationId, !operationId.isEmpty else { continue }
                let methodName = operationId
                let preferred = preferredDefaultResponse(operation: operation, components: components)
                let (statusCode, bodyExpr): (Int, String?) = preferred ?? (204, nil)
                if preferred == nil {
                    let has204 = operation.responses[status: OpenAPI.Response.StatusCode.status(code: 204)] != nil
                    if !has204 {
                        warnToStderr("Kawarimi: operation '\(operationId)' has no 200/201/204 response; generated .noContent stub may not compile. Add at least one of 200, 201, or 204 to the operation.")
                    }
                }
                lines.append("    package func \(methodName)(_ input: Operations.\(methodName).Input) async throws -> Operations.\(methodName).Output {")
                switch statusCode {
                case 200:
                    lines.append("        return .ok(.init(body: .json(\(bodyExpr!))))")
                case 201:
                    lines.append("        return .created(.init(body: .json(\(bodyExpr!))))")
                default:
                    lines.append("        return .noContent(.init())")
                }
                lines.append("    }")
            }
        }
        return lines.joined(separator: "\n")
    }

    /// 200, 201, 204 の順で採用可能な成功レスポンスを選び、(statusCode, bodyExpr?) を返す。204 のときは bodyExpr は nil。
    private static func preferredDefaultResponse(operation: OpenAPI.Operation, components: OpenAPI.Components) -> (Int, String?)? {
        for code in [200, 201] {
            let statusCode = OpenAPI.Response.StatusCode.status(code: code)
            guard let responseEither = operation.responses[status: statusCode],
                  let response = components[responseEither],
                  let expr = bodyExprForResponse(response: response, components: components) else { continue }
            return (code, expr)
        }
        if operation.responses[status: OpenAPI.Response.StatusCode.status(code: 204)] != nil {
            return (204, nil)
        }
        return nil
    }

    private static func bodyExprForResponse(response: OpenAPI.Response, components: OpenAPI.Components) -> String? {
        guard let content = response.content[.json],
              let schema = resolveSchemaFromContent(content: content, components: components) else {
            return nil
        }
        return swiftInitializerForSchema(schema, components: components)
    }

    /// Content の schema (Either<JSONReference<JSONSchema>, JSONSchema>) を解決して JSONSchema を返す。
    private static func resolveSchemaFromContent(content: OpenAPI.Content, components: OpenAPI.Components) -> JSONSchema? {
        guard let schemaEither = content.schema else { return nil }
        switch schemaEither {
        case .a(let ref):
            return components[ref]
        case .b(let schema):
            return schema
        }
    }

    // MARK: - KawarimiSpec 生成

    public static func generateKawarimiSpecSource(document: OpenAPI.Document) -> String {
        let info = document.info
        let title = info.title
        let version = info.version
        let description = info.description

        let serverURLString = document.servers.first?.urlTemplate.rawValue ?? ""
        /// DemoServer の serverURL: "/api" と揃えるため、path は常に "/api" プレフィックス付きで出力する。
        let apiPathPrefix = "/api"

        let components = document.components

        struct ResponseEntry {
            var statusCode: Int
            var contentType: String
            var body: String
            var responseDescription: String?
        }
        struct EndpointEntry {
            var method: String
            var fullPath: String
            var operationId: String
            var responses: [ResponseEntry]
        }

        var endpointEntries: [EndpointEntry] = []

        for route in document.routes {
            let routePath = route.path.rawValue
            let fullPath = apiPathPrefix + (routePath.hasPrefix("/") ? routePath : "/" + routePath)

            for endpoint in route.pathItem.endpoints {
                let operation = endpoint.operation
                guard let operationId = operation.operationId, !operationId.isEmpty else { continue }
                let method = endpoint.method.rawValue.uppercased()

                var responseEntries: [ResponseEntry] = []

                for (statusKey, responseRef) in operation.responses {
                    guard case .status(code: let code) = statusKey.value else { continue }
                    guard let response = components[responseRef] else { continue }

                    if let jsonContent = response.content[.json] {
                        let body = responseBodyJSON(content: jsonContent, components: components)
                        responseEntries.append(ResponseEntry(
                            statusCode: code,
                            contentType: "application/json",
                            body: body,
                            responseDescription: response.description
                        ))
                    } else {
                        responseEntries.append(ResponseEntry(
                            statusCode: code,
                            contentType: "application/json",
                            body: "{}",
                            responseDescription: response.description
                        ))
                    }
                }

                endpointEntries.append(EndpointEntry(
                    method: method,
                    fullPath: fullPath,
                    operationId: operationId,
                    responses: responseEntries
                ))
            }
        }

        // 動的部分を組み立て
        let descLiteral = description.map { "\"\(escapeForSwiftStringLiteral($0))\"" } ?? "nil"
        let serverURLEscaped = escapeForSwiftStringLiteral(serverURLString.isEmpty ? "https://example.com/api" : serverURLString)

        let endpointsLiteral = endpointEntries.map { entry in
            let responsesBlock = entry.responses.map { resp in
                let descVal = resp.responseDescription.map { "\"\(escapeForSwiftStringLiteral($0))\"" } ?? "nil"
                let bodyEsc = escapeForSwiftStringLiteral(resp.body)
                let ctEsc = escapeForSwiftStringLiteral(resp.contentType)
                return """
                        MockResponse(
                            statusCode: \(resp.statusCode),
                            contentType: "\(ctEsc)",
                            body: "\(bodyEsc)",
                            exampleId: nil,
                            summary: nil,
                            description: \(descVal)
                        ),
"""
            }.joined(separator: "\n")
            return """
                    Endpoint(
                        path: "\(escapeForSwiftStringLiteral(entry.fullPath))",
                        method: "\(entry.method)",
                        operationId: "\(escapeForSwiftStringLiteral(entry.operationId))",
                        responses: [
            \(responsesBlock)
                        ]
                    ),
"""
        }.joined(separator: "\n")

        let responseMapLiteral = endpointEntries.map { entry in
            let innerPairs = entry.responses.map { resp in
                let bodyEsc = escapeForSwiftStringLiteral(resp.body)
                let ctEsc = escapeForSwiftStringLiteral(resp.contentType)
                return "\(resp.statusCode): (body: \"\(bodyEsc)\", contentType: \"\(ctEsc)\")"
            }.joined(separator: ", ")
            let key = "\(entry.method):\(entry.fullPath)"
            let keyEsc = escapeForSwiftStringLiteral(key)
            return "                \"\(keyEsc)\": [\(innerPairs)],"
        }.joined(separator: "\n")

        return """
            // Generated by Kawarimi. Do not edit.

            import KawarimiCore

            public enum KawarimiSpec {
                public struct Meta: Codable, Sendable {
                    public var title: String
                    public var version: String
                    public var description: String?
                    public var serverURL: String
                }
                public struct Endpoint: Codable, Sendable {
                    public var path: String
                    public var method: String
                    public var operationId: String
                    public var responses: [MockResponse]
                }
                public struct MockResponse: Codable, Sendable {
                    public var statusCode: Int
                    public var contentType: String
                    public var body: String
                    public var exampleId: String?
                    public var summary: String?
                    public var description: String?
                }

                public static let meta = Meta(
                    title: "\(escapeForSwiftStringLiteral(title))",
                    version: "\(escapeForSwiftStringLiteral(version))",
                    description: \(descLiteral),
                    serverURL: "\(serverURLEscaped)"
                )

                public static let endpoints: [Endpoint] = [
            \(endpointsLiteral)
                ]

                public static let responseMap: [String: [Int: (body: String, contentType: String)]] = [
            \(responseMapLiteral)
                ]
            }

            extension KawarimiSpec.Meta: SpecMetaProviding {}
            extension KawarimiSpec.MockResponse: SpecMockResponseProviding {}
            extension KawarimiSpec.Endpoint: SpecEndpointProviding {
                public var responseList: [any SpecMockResponseProviding] { responses }
            }

            /// DTO for Henge spec API (GET /__kawarimi/spec). Generated by Kawarimi.
            public struct SpecResponse: Codable, Sendable {
                public var meta: KawarimiSpec.Meta
                public var endpoints: [KawarimiSpec.Endpoint]
                public init(meta: KawarimiSpec.Meta, endpoints: [KawarimiSpec.Endpoint]) {
                    self.meta = meta
                    self.endpoints = endpoints
                }
            }
            """
    }

    private static func responseBodyJSON(content: OpenAPI.Content, components: OpenAPI.Components) -> String {
        guard let schemaEither = content.schema else { return "{}" }
        if let ref = schemaEither.reference,
           let name = ref.name,
           let key = OpenAPI.ComponentKey(rawValue: name),
           let schema = components.schemas[key] {
            return defaultJSONForSchema(schema, components: components)
        }
        return "{}"
    }

    private static func swiftInitializerForSchema(_ schema: JSONSchema, components: OpenAPI.Components) -> String {
        let resolved = resolveSchema(schema, components: components) ?? schema

        if let objectContext = resolved.objectContext {
            let args = objectContext.properties.map { name, propSchema -> String in
                let valueExpr = swiftInitializerForSchema(propSchema, components: components)
                return "\(name): \(valueExpr)"
            }
            return ".init(\(args.joined(separator: ", ")))"
        }

        if let arrayContext = resolved.arrayContext {
            guard let itemsSchema = arrayContext.items else { return "[]" }
            let itemExpr = swiftInitializerForSchema(resolveSchema(itemsSchema, components: components) ?? itemsSchema, components: components)
            return "[\(itemExpr)]"
        }

        if let swiftLiteral = exampleToSwiftLiteral(resolved.example, jsonType: resolved.jsonType) {
            return swiftLiteral
        }
        switch resolved.jsonType {
        case .some(.string): return "\"\""
        case .some(.integer): return "0"
        case .some(.number): return "0.0"
        case .some(.boolean): return "false"
        default: return "\"\""
        }
    }

    private static func exampleToSwiftLiteral(_ example: AnyCodable?, jsonType: JSONType?) -> String? {
        guard let example else { return nil }
        guard let data = try? JSONEncoder().encode(example) else { return nil }
        switch jsonType {
        case .string:
            guard let s = try? JSONDecoder().decode(String.self, from: data) else { return nil }
            return "\"\(escapeForSwiftStringLiteral(s))\""
        case .integer:
            guard let i = try? JSONDecoder().decode(Int.self, from: data) else { return nil }
            return "\(i)"
        case .number:
            guard let d = try? JSONDecoder().decode(Double.self, from: data) else { return nil }
            return "\(d)"
        case .boolean:
            guard let b = try? JSONDecoder().decode(Bool.self, from: data) else { return nil }
            return b ? "true" : "false"
        default:
            return nil
        }
    }
}
