import Foundation
import OpenAPIKit30
import Yams

/// ClientTransport モック用 Swift ソースを生成する（本家 Client に渡してテスト用）
public enum KawarimiJutsu {
    /// OpenAPI YAML をパースして Document を返す
    public static func loadOpenAPISpec(path: String) throws -> OpenAPI.Document {
        guard let data = FileManager.default.contents(atPath: path) else {
            throw KawarimiJutsuError.specFileNotFound(path: path)
        }
        guard let content = String(data: data, encoding: .utf8) else {
            throw KawarimiJutsuError.specFileInvalidEncoding
        }
        do {
            return try YAMLDecoder().decode(OpenAPI.Document.self, from: content)
        } catch {
            throw KawarimiJutsuError.specParseError(String(describing: error))
        }
    }

    /// Document から ClientTransport モックの Swift ソースを生成する
    public static func generateSwiftSource(document: OpenAPI.Document, typeName: String = "Kawarimi") -> String {
        let cases = generateTransportCases(document: document)
        return """
            // Generated by Kawarimi. Do not edit.

            import OpenAPIRuntime
            import HTTPTypes

            public struct \(typeName): ClientTransport {
                public init() {}
                public func send(_ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String) async throws -> (HTTPResponse, HTTPBody?) {
                    switch operationID {
            \(cases)
                    default:
                        return (HTTPResponse(status: .notFound), nil)
                    }
                }
            }
            """
    }

    private static func generateTransportCases(document: OpenAPI.Document) -> String {
        var lines: [String] = []
        let components = document.components

        for route in document.routes {
            for endpoint in route.pathItem.endpoints {
                let operation = endpoint.operation
                guard let operationId = operation.operationId, !operationId.isEmpty else { continue }

                let jsonBody = defaultResponseJSON(operation: operation, components: components)
                let escaped = jsonBody.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
                lines.append("                    case \"\(operationId)\":")
                lines.append("                        return (HTTPResponse(status: .ok), HTTPBody(\"\(escaped)\"))")
            }
        }
        return lines.joined(separator: "\n")
    }

    private static func defaultResponseJSON(operation: OpenAPI.Operation, components: OpenAPI.Components) -> String {
        guard let responseEither = operation.responses[status: 200],
              let response = components[responseEither],
              let content = response.content[.json],
              let schemaEither = content.schema else {
            return "{}"
        }
        guard let ref = schemaEither.reference,
              let name = ref.name,
              let key = OpenAPI.ComponentKey(rawValue: name),
              let schema = components.schemas[key],
              let objectContext = schema.objectContext else {
            return "{}"
        }
        let pairs = objectContext.properties.map { name, propSchema -> String in
            let value: String
            switch propSchema.jsonType {
            case .some(.string): value = "\"\""
            case .some(.integer): value = "0"
            case .some(.number): value = "0.0"
            case .some(.boolean): value = "false"
            default: value = "\"\""
            }
            return "\"\(name)\": \(value)"
        }
        return "{\(pairs.joined(separator: ", "))}"
    }

}

public enum KawarimiJutsuError: Error, CustomStringConvertible {
    case specFileNotFound(path: String)
    case specFileInvalidEncoding
    case specParseError(String)

    public var description: String {
        switch self {
        case .specFileNotFound(let path): return "OpenAPI ファイルが見つかりません: \(path)"
        case .specFileInvalidEncoding: return "OpenAPI ファイルのエンコーディングが不正です"
        case .specParseError(let msg): return "OpenAPI のパースに失敗しました: \(msg)"
        }
    }
}
