import Foundation
import OpenAPIKit30
import Yams

/// OpenAPI のパースとモック・ハンドラ用 Swift ソース生成。
public enum KawarimiJutsu {
    public static func loadOpenAPISpec(path: String) throws -> OpenAPI.Document {
        guard let data = FileManager.default.contents(atPath: path) else {
            throw KawarimiJutsuError.specFileNotFound(path: path)
        }
        guard let content = String(data: data, encoding: .utf8) else {
            throw KawarimiJutsuError.specFileInvalidEncoding
        }
        do {
            return try YAMLDecoder().decode(OpenAPI.Document.self, from: content)
        } catch {
            throw KawarimiJutsuError.specParseError(String(describing: error))
        }
    }

    public static func generateSwiftSource(document: OpenAPI.Document) -> String {
        let cases = generateTransportCases(document: document)
        return """
            // Generated by Kawarimi. Do not edit.

            import Foundation
            import OpenAPIRuntime
            import HTTPTypes

            public struct Kawarimi: ClientTransport {
                public init() {}
                public func send(_ request: HTTPRequest, body: HTTPBody?, baseURL: URL, operationID: String) async throws -> (HTTPResponse, HTTPBody?) {
                    switch operationID {
            \(cases)
                    default:
                        return (HTTPResponse(status: .notFound), nil)
                    }
                }
            }
            """
    }

    // MARK: - モック生成の内部

    private static func generateTransportCases(document: OpenAPI.Document) -> String {
        var lines: [String] = []
        let components = document.components

        for route in document.routes {
            for endpoint in route.pathItem.endpoints {
                let operation = endpoint.operation
                guard let operationId = operation.operationId, !operationId.isEmpty else { continue }

                let jsonBody = defaultResponseJSON(operation: operation, components: components)
                let escaped = escapeForSwiftStringLiteral(jsonBody)
                lines.append("                    case \"\(operationId)\":")
                lines.append("                        return (HTTPResponse(status: .ok), HTTPBody(\"\(escaped)\"))")
            }
        }
        return lines.joined(separator: "\n")
    }

    private static func escapeForSwiftStringLiteral(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
    }

    private static func defaultResponseJSON(operation: OpenAPI.Operation, components: OpenAPI.Components) -> String {
        guard let responseEither = operation.responses[status: 200],
              let response = components[responseEither],
              let content = response.content[.json],
              let schemaEither = content.schema else {
            return "{}"
        }
        guard let ref = schemaEither.reference,
              let name = ref.name,
              let key = OpenAPI.ComponentKey(rawValue: name),
              let schema = components.schemas[key] else {
            return "{}"
        }
        return defaultJSONForSchema(schema, components: components)
    }

    private static func resolveSchema(_ schema: JSONSchema, components: OpenAPI.Components) -> JSONSchema? {
        guard case .reference(let ref, _) = schema.value,
              let name = ref.name,
              let key = OpenAPI.ComponentKey(rawValue: name) else {
            return schema
        }
        return components.schemas[key]
    }

    private static func defaultJSONForSchema(_ schema: JSONSchema, components: OpenAPI.Components) -> String {
        let resolved = resolveSchema(schema, components: components) ?? schema

        if let objectContext = resolved.objectContext {
            let pairs = objectContext.properties.map { name, propSchema -> String in
                let value = defaultJSONForSchema(propSchema, components: components)
                return "\"\(name)\": \(value)"
            }
            return "{\(pairs.joined(separator: ", "))}"
        }

        if let arrayContext = resolved.arrayContext {
            guard let itemsSchema = arrayContext.items else {
                return "[]"
            }
            let resolvedItem = resolveSchema(itemsSchema, components: components) ?? itemsSchema
            let itemJSON = defaultJSONForSchema(resolvedItem, components: components)
            return "[\(itemJSON)]"
        }

        switch resolved.jsonType {
        case .some(.string): return "\"\""
        case .some(.integer): return "0"
        case .some(.number): return "0.0"
        case .some(.boolean): return "false"
        default: return "\"\""
        }
    }

    public static func generateKawarimiHandlerSource(document: OpenAPI.Document) -> String {
        let methods = generateHandlerMethods(document: document)
        return """
            // Generated by Kawarimi. Do not edit.

            import Foundation
            import OpenAPIRuntime
            import HTTPTypes

            public struct KawarimiHandler: APIProtocol {
                public init() {}
            \(methods)
            }
            """
    }

    private static func generateHandlerMethods(document: OpenAPI.Document) -> String {
        var lines: [String] = []
        let components = document.components

        for route in document.routes {
            for endpoint in route.pathItem.endpoints {
                let operation = endpoint.operation
                guard let operationId = operation.operationId, !operationId.isEmpty else { continue }
                let methodName = operationId
                guard let bodyExpr = defaultResponseBodyExpr(operation: operation, components: components) else { continue }
                lines.append("    package func \(methodName)(_ input: Operations.\(methodName).Input) async throws -> Operations.\(methodName).Output {")
                lines.append("        return .ok(.init(body: .json(\(bodyExpr))))")
                lines.append("    }")
            }
        }
        return lines.joined(separator: "\n")
    }

    private static func defaultResponseBodyExpr(operation: OpenAPI.Operation, components: OpenAPI.Components) -> String? {
        guard let responseEither = operation.responses[status: 200],
              let response = components[responseEither],
              let content = response.content[.json],
              let schemaEither = content.schema else {
            return nil
        }
        guard let ref = schemaEither.reference,
              let name = ref.name,
              let key = OpenAPI.ComponentKey(rawValue: name),
              let schema = components.schemas[key] else {
            return nil
        }
        return swiftInitializerForSchema(schema, components: components)
    }

    private static func swiftInitializerForSchema(_ schema: JSONSchema, components: OpenAPI.Components) -> String {
        let resolved = resolveSchema(schema, components: components) ?? schema

        if let objectContext = resolved.objectContext {
            let args = objectContext.properties.map { name, propSchema -> String in
                let valueExpr = swiftInitializerForSchema(propSchema, components: components)
                return "\(name): \(valueExpr)"
            }
            return ".init(\(args.joined(separator: ", ")))"
        }

        if let arrayContext = resolved.arrayContext {
            guard let itemsSchema = arrayContext.items else { return "[]" }
            let itemExpr = swiftInitializerForSchema(resolveSchema(itemsSchema, components: components) ?? itemsSchema, components: components)
            return "[\(itemExpr)]"
        }

        switch resolved.jsonType {
        case .some(.string): return "\"\""
        case .some(.integer): return "0"
        case .some(.number): return "0.0"
        case .some(.boolean): return "false"
        default: return "\"\""
        }
    }
}
