#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="$(git -C "$ROOT" describe --tags --always)"
cat > "$ROOT/Sources/Kawarimi/Generated.swift" <<EOF_SWIFT
// Generated by Scripts/generate-build-info.sh — do not edit.
enum BuildInfo {
    static let version = "$VERSION"
}
EOF_SWIFT
