name: Performance

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6

      - name: Incremental build
        run: ./Scripts/performance/incremental-build.sh --clean
